# StatsPAI Causal Inference Demo — Interactive Edition

This notebook demonstrates core causal inference methods with **interactive plot editing**.

Every plot opens with `sp.interactive(fig)` — an ipywidgets control panel where you can:
- Edit titles, labels, fonts, colors, line styles
- Adjust DPI, figure size, tick rotation, background
- Add annotations, toggle grid/legend/spines
- Generate reproducible code for all edits

**Methods covered:**

1. **Difference-in-Differences (DID)** — Classic 2×2 and Event Study
2. **Fixed Effects (FE)** — Panel data with entity fixed effects
3. **Instrumental Variables (IV)** — 2SLS estimation
4. **Matching** — Propensity score matching
5. **Synthetic Control (SC)** — Abadie-style SCM
6. **Regression Discontinuity (RDD)** — Sharp RD design
7. **Binscatter** — Non-parametric conditional means

---

# StatsPAI 因果推断演示 — 交互式版本

本 Notebook 展示了核心因果推断方法，并支持**交互式图表编辑**。

每张图表都通过 `sp.interactive(fig)` 打开一个 ipywidgets 控制面板，您可以：
- 编辑标题、标签、字体、颜色、线条样式
- 调整 DPI、图形大小、刻度旋转、背景色
- 添加注释，切换网格/图例/边框
- 生成所有编辑的可复现代码

**涵盖的方法：**

1. **双重差分法 (DID)** — 经典 2×2 设计与事件研究
2. **固定效应模型 (FE)** — 面板数据实体固定效应
3. **工具变量法 (IV)** — 两阶段最小二乘估计
4. **匹配法 (Matching)** — 倾向得分匹配
5. **合成控制法 (SC)** — Abadie 式合成控制
6. **断点回归设计 (RDD)** — 精确断点回归
7. **分箱散点图 (Binscatter)** — 非参数条件均值可视化

In [1]:
# 导入依赖库并设置随机种子和学术主题
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statspai as sp

np.random.seed(42)
sp.set_theme('academic')
%matplotlib inline

---
## 1. Difference-in-Differences (DID)

Classic 2×2 DID with parallel trends visualization, then staggered adoption event study.

---
## 1. 双重差分法 (DID)

经典 2×2 双重差分设计，包含平行趋势可视化和交错处理事件研究。

In [2]:
# 模拟 DID 数据：2×2 设计
# 200 个个体，10 个时间段，处理组从 t=6 开始接受处理
# Simulate DID data: 2×2 design
# 200 individuals, 10 time periods, treatment starts at t=6 for treated group
n_did = 200
t_periods = 10
ids = np.repeat(np.arange(n_did), t_periods)
times = np.tile(np.arange(1, t_periods + 1), n_did)
treat_group = (ids < 100).astype(int)  # first 100 = treated
post = (times >= 6).astype(int)

# Parallel trends in pre-period, treatment effect = 3.0 in post
individual_fe = np.repeat(np.random.normal(0, 2, n_did), t_periods)
time_trend = 0.5 * times
y_did = 10 + 2 * treat_group + time_trend + 3.0 * treat_group * post + individual_fe + np.random.normal(0, 1.5, n_did * t_periods)

df_did = pd.DataFrame({
    'id': ids, 'time': times, 'treated': treat_group,
    'post': post, 'outcome': y_did,
    'x1': np.random.normal(0, 1, n_did * t_periods),
})
print(f"Shape: {df_did.shape}, Treated units: {(ids < 100).sum() // t_periods}")
df_did.head()

Shape: (2000, 6), Treated units: 100

   id  time  treated  post    outcome        x1
0   0     1        1     0  14.030109  1.804348
1   0     2        1     0  14.834605 -0.190904
2   0     3        1     0  16.118005  0.719758
3   0     4        1     0  16.574131 -1.293273
4   0     5        1     0  13.426924 -0.956436

In [3]:
# 2×2 双重差分估计
# 2×2 DID estimation
did_result = sp.did(
    df_did, y='outcome', treat='treated', time='time',
    id='id', method='classic'
)
did_result

In [4]:
# 绘图 1：DID 平行趋势 — 处理组与控制组各期均值
# Plot 1: DID parallel trends — treated vs control group means over time
fig, ax = sp.did_plot(
    df_did, y='outcome', time='time', treat='treated',
    treat_time=6,
    labels={'treated': 'Treatment Group', 'control': 'Control Group'},
    title='DID: Parallel Trends & Treatment Effect',
    annotate_effect=True,
)
# # --- StatsPAI interactive edits (paste after your plot code) ---
# import statspai as sp
# sp.set_theme('ggplot')
# fig.tight_layout()
# # --- end StatsPAI edits ---

sp.interactive(fig)

HBox(children=(VBox(children=(Image(value=b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x03\xdc\x00\x00\x02I\x…

FigureEditor(fig=<Figure size 1500x900 with 1 Axes>, protect_data=True, edits=[], artist_roles={5052208016: <ArtistRole.LABEL: 5>, 5070435024: <ArtistRole.LABEL: 5>, 5070436432: <ArtistRole.LABEL: 5>, 5051343120: <ArtistRole.SPINE: 8>, 5070430736: <ArtistRole.SPINE: 8>, 5070431952: <ArtistRole.SPINE: 8>, 5070433104: <ArtistRole.SPINE: 8>, 5051339664: <ArtistRole.LEGEND: 7>, 5051403216: <ArtistRole.DATA: 1>, 5070688016: <ArtistRole.REFERENCE: 4>, 5070693008: <ArtistRole.DATA: 1>, 5051346320: <ArtistRole.REFERENCE: 4>, 5070699088: <ArtistRole.ANNOTATION: 6>, 5070525264: <ArtistRole.ANNOTATION: 6>, 4464028688: <ArtistRole.ANNOTATION: 6>}, _original_state={'ax.title.text': 'DID: Parallel Trends & Treatment Effect', 'ax.title.fontsize': 13.0, 'ax.title.color': 'black', 'ax.title.fontweight': 'normal', 'ax.xlabel.text': 'Time', 'ax.xlabel.fontsize': 11.0, 'ax.xlabel.color': 'black', 'ax.ylabel.text': 'Outcome', 'ax.ylabel.fontsize': 11.0, 'ax.ylabel.color': 'black', 'ax.xlim': (np.float64(0.55), np.float64(10.45)), 'ax.ylim': (np.float64(10.157882537037665), np.float64(20.502018931687)), 'ax.facecolor': (1.0, 1.0, 1.0, 1.0), 'ax.xtick_rotation': 0.0, 'ax.ytick_rotation': 0.0, 'ax.spines.left.visible': True, 'ax.spines.right.visible': False, 'ax.spines.bottom.visible': True, 'ax.spines.top.visible': False, 'ax.grid': False, 'ax.line0.color': '#2C3E50', 'ax.line0.linewidth': 2.0, 'ax.line0.linestyle': '-', 'ax.line0.alpha': None, 'ax.line0.marker': 's', 'ax.line1.color': '#E74C3C', 'ax.line1.linewidth': 2.0, 'ax.line1.linestyle': '-', 'ax.line1.alpha': None, 'ax.line1.marker': 'o', 'ax.line2.color': '#E74C3C', 'ax.line2.linewidth': 1.5, 'ax.line2.linestyle': '--', 'ax.line2.alpha': 0.7, 'ax.line2.marker': '', 'ax.line3.color': 'gray', 'ax.line3.linewidth': 1.0, 'ax.line3.linestyle': ':', 'ax.line3.alpha': 0.5, 'ax.line3.marker': 'None', 'ax.n_texts': 3, 'fig.figsize': (np.float64(10.0), np.float64(6.0)), 'fig.dpi': 150.0, 'fig.facecolor': (1.0, 1.0, 1.0, 1.0)}, _on_refresh_callbacks=[<function create_jupyter_panel.<locals>._live_refresh at 0x12ea20400>, <function create_jupyter_panel.<locals>._live_history_update at 0x12eaf72e0>, <function create_jupyter_panel.<locals>._live_code_update at 0x12eb402c0>], _redo_stack=[])

In [5]:
# 绘图 2：使用 Callaway-Sant'Anna 方法的事件研究
# 需要交错处理编码：first_treat = 首次处理时期（0 = 从未处理）
# Plot 2: Event study using Callaway-Sant'Anna
# Need staggered treatment coding: first_treat = period of first treatment (0 = never treated)
df_did['first_treat'] = np.where(df_did['treated'] == 1, 6, 0)

es_result = sp.did(
    df_did, y='outcome', treat='first_treat', time='time',
    id='id', method='cs'
)
fig, ax = es_result.plot(type='event_study',
    title='DID Event Study: Dynamic Treatment Effects',
    color='#1a5276',
)
sp.interactive(fig)

HBox(children=(VBox(children=(Image(value=b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x03\xda\x00\x00\x02I\x…

FigureEditor(fig=<Figure size 1500x900 with 1 Axes>, protect_data=True, edits=[], artist_roles={5077426960: <ArtistRole.LABEL: 5>, 5078185552: <ArtistRole.LABEL: 5>, 4387152592: <ArtistRole.LABEL: 5>, 5077950224: <ArtistRole.SPINE: 8>, 5078177744: <ArtistRole.SPINE: 8>, 5077299728: <ArtistRole.SPINE: 8>, 5077295056: <ArtistRole.SPINE: 8>, 5078690576: <ArtistRole.LEGEND: 7>, 5076699408: <ArtistRole.DATA: 1>, 5037194448: <ArtistRole.REFERENCE: 4>, 5078501840: <ArtistRole.REFERENCE: 4>, 5078066576: <ArtistRole.REFERENCE: 4>, 5078686992: <ArtistRole.REFERENCE: 4>, 5078488592: <ArtistRole.CI: 3>, 5077121232: <ArtistRole.DATA: 1>, 5077117712: <ArtistRole.CI: 3>}, _original_state={'ax.title.text': 'DID Event Study: Dynamic Treatment Effects', 'ax.title.fontsize': 13.0, 'ax.title.color': 'black', 'ax.title.fontweight': 'normal', 'ax.xlabel.text': 'Periods Relative to Treatment', 'ax.xlabel.fontsize': 11.0, 'ax.xlabel.color': 'black', 'ax.ylabel.text': 'Estimated Effect', 'ax.ylabel.fontsize': 11.0, 'ax.ylabel.color': 'black', 'ax.xlim': (np.float64(-5.45), np.float64(4.45)), 'ax.ylim': (np.float64(-1.365419279546503), np.float64(3.744231062105696)), 'ax.facecolor': (1.0, 1.0, 1.0, 1.0), 'ax.xtick_rotation': 0.0, 'ax.ytick_rotation': 0.0, 'ax.spines.left.visible': True, 'ax.spines.right.visible': False, 'ax.spines.bottom.visible': True, 'ax.spines.top.visible': False, 'ax.grid': False, 'ax.line0.color': '#1a5276', 'ax.line0.linewidth': 1.0, 'ax.line0.linestyle': '-', 'ax.line0.alpha': 0.7, 'ax.line0.marker': 'None', 'ax.line1.color': '#1a5276', 'ax.line1.linewidth': 1.0, 'ax.line1.linestyle': 'None', 'ax.line1.alpha': None, 'ax.line1.marker': '_', 'ax.line2.color': '#1a5276', 'ax.line2.linewidth': 1.0, 'ax.line2.linestyle': 'None', 'ax.line2.alpha': None, 'ax.line2.marker': '_', 'ax.line3.color': 'gray', 'ax.line3.linewidth': 0.8, 'ax.line3.linestyle': '--', 'ax.line3.alpha': None, 'ax.line3.marker': 'None', 'ax.line4.color': '#E74C3C', 'ax.line4.linewidth': 1.0, 'ax.line4.linestyle': ':', 'ax.line4.alpha': 0.5, 'ax.line4.marker': 'None', 'ax.coll0.alpha': 0.15, 'ax.coll0.facecolors': array([[0.10196078, 0.32156863, 0.4627451 , 0.15      ]]), 'ax.coll1.alpha': None, 'ax.coll1.facecolors': array([[0.10196078, 0.32156863, 0.4627451 , 1.        ]]), 'ax.coll2.alpha': None, 'ax.coll2.facecolors': array([], shape=(0, 4), dtype=float64), 'ax.n_texts': 0, 'fig.figsize': (np.float64(10.0), np.float64(6.0)), 'fig.dpi': 150.0, 'fig.facecolor': (1.0, 1.0, 1.0, 1.0)}, _on_refresh_callbacks=[<function create_jupyter_panel.<locals>._live_refresh at 0x12eb13060>, <function create_jupyter_panel.<locals>._live_history_update at 0x12ec79e40>, <function create_jupyter_panel.<locals>._live_code_update at 0x12ec7ade0>], _redo_stack=[])

---
## 2. Fixed Effects (FE)

Panel data: 100 firms observed over 10 years. Treatment `policy` is staggered.

---
## 2. 固定效应模型 (FE)

面板数据：100 家企业观测 10 年。处理变量 `policy`（政策）采用交错实施。

In [6]:
# 模拟面板数据：100 家企业，10 年
# Simulate panel data
n_firms, n_years = 100, 10
firms = np.repeat(np.arange(n_firms), n_years)
years = np.tile(np.arange(2010, 2010 + n_years), n_firms)
firm_fe = np.repeat(np.random.normal(0, 2, n_firms), n_years)
x1 = np.random.normal(5, 1, n_firms * n_years)
x2 = np.random.normal(0, 1, n_firms * n_years)
policy = ((years >= 2015) & (firms < 50)).astype(int)
y_panel = 3 + 2.5 * x1 - 1.2 * x2 + 1.8 * policy + firm_fe + np.random.normal(0, 1, n_firms * n_years)

df_panel = pd.DataFrame({
    'firm_id': firms, 'year': years,
    'revenue': y_panel, 'investment': x1, 'debt_ratio': x2, 'policy': policy
})
df_panel.head()

   firm_id  year    revenue  investment  debt_ratio  policy
0        0  2010  14.957120    4.576401   -0.208668       0
1        0  2011  11.507491    3.634383   -0.312668       0
2        0  2012  13.481348    4.025878    0.857899       0
3        0  2013  18.209287    5.703428    0.553570       0
4        0  2014  11.080308    3.692630   -0.257300       0

In [7]:
# 固定效应回归
# Fixed Effects regression
fe_result = sp.panel(
    df_panel,
    "revenue ~ investment + debt_ratio + policy",
    entity='firm_id', time='year', method='fe'
)
fe_result

In [8]:
# Hausman 检验：固定效应 vs 随机效应
# Hausman test: FE vs RE
fe_result.hausman_test()

{'statistic': 0.29638622861747155,
 'df': 3,
 'pvalue': 0.9607066942780254,
 'recommendation': 'RE',
 'beta_fe': investment    2.532736
 debt_ratio   -1.168082
 policy        2.013911
 dtype: float64,
 'beta_re': investment    2.532659
 debt_ratio   -1.168357
 policy        2.009315
 dtype: float64,
 'interpretation': 'chi2(3) = 0.2964, p = 0.9607. Cannot reject H0: Random Effects is more efficient.'}

In [9]:
# 绘图：系数森林图
# Plot: Coefficient forest plot
fig, ax = sp.coefplot(fe_result, title='Fixed Effects: Coefficient Plot')
sp.interactive(fig)

HBox(children=(VBox(children=(Image(value=b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x03\x12\x00\x00\x02I\x…

FigureEditor(fig=<Figure size 1200x900 with 1 Axes>, protect_data=True, edits=[], artist_roles={5095809168: <ArtistRole.LABEL: 5>, 5095800976: <ArtistRole.LABEL: 5>, 5095803344: <ArtistRole.LABEL: 5>, 5079178448: <ArtistRole.SPINE: 8>, 5095723728: <ArtistRole.SPINE: 8>, 5095732368: <ArtistRole.SPINE: 8>, 5095733520: <ArtistRole.SPINE: 8>, 5095804624: <ArtistRole.LEGEND: 7>, 5095651280: <ArtistRole.REFERENCE: 4>, 5095843728: <ArtistRole.REFERENCE: 4>, 5095596048: <ArtistRole.REFERENCE: 4>, 5095602384: <ArtistRole.DATA: 1>, 5095721168: <ArtistRole.CI: 3>}, _original_state={'ax.title.text': 'Fixed Effects: Coefficient Plot', 'ax.title.fontsize': 13.0, 'ax.title.color': 'black', 'ax.title.fontweight': 'normal', 'ax.xlabel.text': 'Coefficient Estimate', 'ax.xlabel.fontsize': 11.0, 'ax.xlabel.color': 'black', 'ax.ylabel.text': '', 'ax.ylabel.fontsize': 11.0, 'ax.ylabel.color': 'black', 'ax.xlim': (np.float64(-1.4270658370199154), np.float64(2.7936456216609726)), 'ax.ylim': (np.float64(2.1), np.float64(-0.1)), 'ax.facecolor': (1.0, 1.0, 1.0, 1.0), 'ax.xtick_rotation': 0.0, 'ax.ytick_rotation': 0.0, 'ax.spines.left.visible': True, 'ax.spines.right.visible': False, 'ax.spines.bottom.visible': True, 'ax.spines.top.visible': False, 'ax.grid': False, 'ax.line0.color': '#2C3E50', 'ax.line0.linewidth': 1.0, 'ax.line0.linestyle': 'None', 'ax.line0.alpha': None, 'ax.line0.marker': '|', 'ax.line1.color': '#2C3E50', 'ax.line1.linewidth': 1.0, 'ax.line1.linestyle': 'None', 'ax.line1.alpha': None, 'ax.line1.marker': '|', 'ax.line2.color': 'gray', 'ax.line2.linewidth': 0.8, 'ax.line2.linestyle': '--', 'ax.line2.alpha': None, 'ax.line2.marker': 'None', 'ax.coll0.alpha': None, 'ax.coll0.facecolors': array([[0.17254902, 0.24313725, 0.31372549, 1.        ]]), 'ax.coll1.alpha': None, 'ax.coll1.facecolors': array([], shape=(0, 4), dtype=float64), 'ax.n_texts': 0, 'fig.figsize': (np.float64(8.0), np.float64(6.0)), 'fig.dpi': 150.0, 'fig.facecolor': (1.0, 1.0, 1.0, 1.0)}, _on_refresh_callbacks=[<function create_jupyter_panel.<locals>._live_refresh at 0x12fbf63e0>, <function create_jupyter_panel.<locals>._live_history_update at 0x12fd64b80>, <function create_jupyter_panel.<locals>._live_code_update at 0x12fd65b20>], _redo_stack=[])

In [10]:
# 绘图：对比固定效应、随机效应和混合回归的系数
# Plot: Compare FE vs RE vs Pooled coefficients
re_result = sp.panel(df_panel, "revenue ~ investment + debt_ratio + policy",
                     entity='firm_id', time='year', method='re')
pooled_result = sp.panel(df_panel, "revenue ~ investment + debt_ratio + policy",
                         entity='firm_id', time='year', method='pooled')

fig, ax = sp.coefplot(fe_result, re_result, pooled_result,
                      model_names=['FE', 'RE', 'Pooled'],
                      title='Panel Models: Coefficient Comparison')
sp.interactive(fig)

HBox(children=(VBox(children=(Image(value=b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x03\x12\x00\x00\x02I\x…

FigureEditor(fig=<Figure size 1200x900 with 1 Axes>, protect_data=True, edits=[], artist_roles={5096740752: <ArtistRole.LABEL: 5>, 5097670160: <ArtistRole.LABEL: 5>, 5097670992: <ArtistRole.LABEL: 5>, 5097762576: <ArtistRole.SPINE: 8>, 5097402256: <ArtistRole.SPINE: 8>, 5096618704: <ArtistRole.SPINE: 8>, 5096619856: <ArtistRole.SPINE: 8>, 5097672400: <ArtistRole.LEGEND: 7>, 5097762768: <ArtistRole.REFERENCE: 4>, 5097837840: <ArtistRole.REFERENCE: 4>, 5097845648: <ArtistRole.REFERENCE: 4>, 5097918288: <ArtistRole.REFERENCE: 4>, 5096865104: <ArtistRole.REFERENCE: 4>, 5096274320: <ArtistRole.REFERENCE: 4>, 5097760016: <ArtistRole.REFERENCE: 4>, 5096931152: <ArtistRole.DATA: 1>, 5097807888: <ArtistRole.CI: 3>, 5097836688: <ArtistRole.DATA: 1>, 5096606480: <ArtistRole.CI: 3>, 5097923408: <ArtistRole.DATA: 1>, 5097848528: <ArtistRole.CI: 3>}, _original_state={'ax.title.text': 'Panel Models: Coefficient Comparison', 'ax.title.fontsize': 13.0, 'ax.title.color': 'black', 'ax.title.fontweight': 'normal', 'ax.xlabel.text': 'Coefficient Estimate', 'ax.xlabel.fontsize': 11.0, 'ax.xlabel.color': 'black', 'ax.ylabel.text': '', 'ax.ylabel.fontsize': 11.0, 'ax.ylabel.color': 'black', 'ax.xlim': (np.float64(-1.5513547099021268), np.float64(3.5020405504400878)), 'ax.ylim': (np.float64(3.465), np.float64(-0.165)), 'ax.facecolor': (1.0, 1.0, 1.0, 1.0), 'ax.xtick_rotation': 0.0, 'ax.ytick_rotation': 0.0, 'ax.spines.left.visible': True, 'ax.spines.right.visible': False, 'ax.spines.bottom.visible': True, 'ax.spines.top.visible': False, 'ax.grid': False, 'ax.line0.color': '#2C3E50', 'ax.line0.linewidth': 1.0, 'ax.line0.linestyle': 'None', 'ax.line0.alpha': None, 'ax.line0.marker': '|', 'ax.line1.color': '#2C3E50', 'ax.line1.linewidth': 1.0, 'ax.line1.linestyle': 'None', 'ax.line1.alpha': None, 'ax.line1.marker': '|', 'ax.line2.color': '#E74C3C', 'ax.line2.linewidth': 1.0, 'ax.line2.linestyle': 'None', 'ax.line2.alpha': None, 'ax.line2.marker': '|', 'ax.line3.color': '#E74C3C', 'ax.line3.linewidth': 1.0, 'ax.line3.linestyle': 'None', 'ax.line3.alpha': None, 'ax.line3.marker': '|', 'ax.line4.color': '#3498DB', 'ax.line4.linewidth': 1.0, 'ax.line4.linestyle': 'None', 'ax.line4.alpha': None, 'ax.line4.marker': '|', 'ax.line5.color': '#3498DB', 'ax.line5.linewidth': 1.0, 'ax.line5.linestyle': 'None', 'ax.line5.alpha': None, 'ax.line5.marker': '|', 'ax.line6.color': 'gray', 'ax.line6.linewidth': 0.8, 'ax.line6.linestyle': '--', 'ax.line6.alpha': None, 'ax.line6.marker': 'None', 'ax.coll0.alpha': None, 'ax.coll0.facecolors': array([[0.17254902, 0.24313725, 0.31372549, 1.        ]]), 'ax.coll1.alpha': None, 'ax.coll1.facecolors': array([], shape=(0, 4), dtype=float64), 'ax.coll2.alpha': None, 'ax.coll2.facecolors': array([[0.90588235, 0.29803922, 0.23529412, 1.        ]]), 'ax.coll3.alpha': None, 'ax.coll3.facecolors': array([], shape=(0, 4), dtype=float64), 'ax.coll4.alpha': None, 'ax.coll4.facecolors': array([[0.20392157, 0.59607843, 0.85882353, 1.        ]]), 'ax.coll5.alpha': None, 'ax.coll5.facecolors': array([], shape=(0, 4), dtype=float64), 'ax.n_texts': 0, 'fig.figsize': (np.float64(8.0), np.float64(6.0)), 'fig.dpi': 150.0, 'fig.facecolor': (1.0, 1.0, 1.0, 1.0)}, _on_refresh_callbacks=[<function create_jupyter_panel.<locals>._live_refresh at 0x12fe00400>, <function create_jupyter_panel.<locals>._live_history_update at 0x12fee6840>, <function create_jupyter_panel.<locals>._live_code_update at 0x12fee77e0>], _redo_stack=[])

---
## 3. Instrumental Variables (IV)

Classic returns-to-education example: `education` is endogenous, `distance_to_college` is the instrument.

---
## 3. 工具变量法 (IV)

经典的教育回报率案例：`education`（教育年限）为内生变量，`distance_to_college`（到大学的距离）为工具变量。

In [11]:
# 模拟工具变量数据
# ability（能力）为不可观测变量，distance（距离）为工具变量
# Simulate IV data
n_iv = 2000
ability = np.random.normal(0, 1, n_iv)  # unobserved
distance = np.random.normal(50, 20, n_iv)  # instrument
experience = np.random.normal(10, 3, n_iv)
education = 16 - 0.08 * distance + 0.5 * ability + np.random.normal(0, 1, n_iv)
wage = 10 + 0.8 * education + 0.3 * experience + 0.6 * ability + np.random.normal(0, 2, n_iv)

df_iv = pd.DataFrame({
    'wage': wage, 'education': education,
    'experience': experience, 'distance': distance
})
df_iv.head()

        wage  education  experience   distance
0  16.860593  11.152590   10.657927  58.424948
1  23.263697  10.456267   10.105886  66.936799
2  21.417441  10.372786    7.831496  60.686944
3  23.347924  15.824814    3.473354  14.631691
4  20.524002   8.772993    7.021394  69.903353

In [12]:
# OLS 回归（因遗漏能力变量而存在偏误）
# OLS (biased due to omitted ability)
ols_result = sp.regress("wage ~ education + experience", data=df_iv)
ols_result

In [13]:
# 两阶段最小二乘 (2SLS) 工具变量估计
# 公式：y ~ (内生变量 ~ 工具变量) + 外生控制变量
# 2SLS IV estimation
# Formula: y ~ (endogenous ~ instruments) + exogenous_controls
iv_result = sp.iv(
    "wage ~ (education ~ distance) + experience",
    data=df_iv
)
iv_result

In [14]:
# 绘图：并排比较 OLS 与 IV 系数
# Plot: Compare OLS vs IV coefficients side by side
fig, ax = sp.coefplot(ols_result, iv_result,
                      model_names=['OLS (biased)', '2SLS IV (consistent)'],
                      colors=['#E74C3C', '#2C3E50'],
                      title='OLS vs IV: Returns to Education')
sp.interactive(fig)

HBox(children=(VBox(children=(Image(value=b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x03\x12\x00\x00\x02I\x…

FigureEditor(fig=<Figure size 1200x900 with 1 Axes>, protect_data=True, edits=[], artist_roles={5282398544: <ArtistRole.LABEL: 5>, 5282371664: <ArtistRole.LABEL: 5>, 5282374608: <ArtistRole.LABEL: 5>, 5282365712: <ArtistRole.SPINE: 8>, 5282367120: <ArtistRole.SPINE: 8>, 5282368464: <ArtistRole.SPINE: 8>, 5282369616: <ArtistRole.SPINE: 8>, 5282667088: <ArtistRole.LEGEND: 7>, 5098865808: <ArtistRole.REFERENCE: 4>, 5282633680: <ArtistRole.REFERENCE: 4>, 5282641680: <ArtistRole.REFERENCE: 4>, 5282668432: <ArtistRole.REFERENCE: 4>, 5282641744: <ArtistRole.REFERENCE: 4>, 5282557392: <ArtistRole.DATA: 1>, 5282560208: <ArtistRole.CI: 3>, 5282639696: <ArtistRole.DATA: 1>, 5282305104: <ArtistRole.CI: 3>}, _original_state={'ax.title.text': 'OLS vs IV: Returns to Education', 'ax.title.fontsize': 13.0, 'ax.title.color': 'black', 'ax.title.fontweight': 'normal', 'ax.xlabel.text': 'Coefficient Estimate', 'ax.xlabel.fontsize': 11.0, 'ax.xlabel.color': 'black', 'ax.ylabel.text': '', 'ax.ylabel.fontsize': 11.0, 'ax.ylabel.color': 'black', 'ax.xlim': (np.float64(-0.27680929249161784), np.float64(11.350446720080766)), 'ax.ylim': (np.float64(2.2649999999999997), np.float64(-0.265)), 'ax.facecolor': (1.0, 1.0, 1.0, 1.0), 'ax.xtick_rotation': 0.0, 'ax.ytick_rotation': 0.0, 'ax.spines.left.visible': True, 'ax.spines.right.visible': False, 'ax.spines.bottom.visible': True, 'ax.spines.top.visible': False, 'ax.grid': False, 'ax.line0.color': '#E74C3C', 'ax.line0.linewidth': 1.0, 'ax.line0.linestyle': 'None', 'ax.line0.alpha': None, 'ax.line0.marker': '|', 'ax.line1.color': '#E74C3C', 'ax.line1.linewidth': 1.0, 'ax.line1.linestyle': 'None', 'ax.line1.alpha': None, 'ax.line1.marker': '|', 'ax.line2.color': '#2C3E50', 'ax.line2.linewidth': 1.0, 'ax.line2.linestyle': 'None', 'ax.line2.alpha': None, 'ax.line2.marker': '|', 'ax.line3.color': '#2C3E50', 'ax.line3.linewidth': 1.0, 'ax.line3.linestyle': 'None', 'ax.line3.alpha': None, 'ax.line3.marker': '|', 'ax.line4.color': 'gray', 'ax.line4.linewidth': 0.8, 'ax.line4.linestyle': '--', 'ax.line4.alpha': None, 'ax.line4.marker': 'None', 'ax.coll0.alpha': None, 'ax.coll0.facecolors': array([[0.90588235, 0.29803922, 0.23529412, 1.        ]]), 'ax.coll1.alpha': None, 'ax.coll1.facecolors': array([], shape=(0, 4), dtype=float64), 'ax.coll2.alpha': None, 'ax.coll2.facecolors': array([[0.17254902, 0.24313725, 0.31372549, 1.        ]]), 'ax.coll3.alpha': None, 'ax.coll3.facecolors': array([], shape=(0, 4), dtype=float64), 'ax.n_texts': 0, 'fig.figsize': (np.float64(8.0), np.float64(6.0)), 'fig.dpi': 150.0, 'fig.facecolor': (1.0, 1.0, 1.0, 1.0)}, _on_refresh_callbacks=[<function create_jupyter_panel.<locals>._live_refresh at 0x13adfe2a0>, <function create_jupyter_panel.<locals>._live_history_update at 0x13af551c0>, <function create_jupyter_panel.<locals>._live_code_update at 0x13af560c0>], _redo_stack=[])

---
## 4. Matching

Job training program evaluation: estimate ATT using propensity score matching.

---
## 4. 匹配法 (Matching)

就业培训项目评估：使用倾向得分匹配估计处理组平均处理效应（ATT）。

In [15]:
# 模拟匹配数据：就业培训项目
# Simulate matching data
n_match = 1000
age = np.random.normal(35, 8, n_match)
edu_years = np.random.normal(12, 3, n_match)
prior_earn = np.random.normal(30000, 8000, n_match)

# Treatment assignment depends on covariates (selection bias)
propensity = 1 / (1 + np.exp(-(- 2 + 0.05 * age - 0.1 * edu_years + 0.00005 * prior_earn)))
treatment = np.random.binomial(1, propensity)

# Outcome: treatment effect = 2000
earnings = 25000 + 500 * edu_years + 100 * age + 0.5 * prior_earn + 2000 * treatment + np.random.normal(0, 3000, n_match)

df_match = pd.DataFrame({
    'earnings': earnings, 'treatment': treatment,
    'age': age, 'edu_years': edu_years, 'prior_earn': prior_earn
})
print(f"Treated: {treatment.sum()}, Control: {(1-treatment).sum()}")
df_match.head()

Treated: 485, Control: 515

       earnings  treatment        age  edu_years    prior_earn
0  52592.516393          1  20.702891  13.150965  41327.285124
1  51203.815118          1  26.931754   9.365591  38008.518741
2  45276.029806          0  33.025137   8.042484  32374.616868
3  51692.670654          0  22.516532  11.528465  28293.692693
4  56786.043023          0  43.897193  10.427315  36819.271022

In [16]:
# 倾向得分匹配
# Propensity Score Matching
match_result = sp.match(
    df_match,
    y='earnings', treat='treatment',
    covariates=['age', 'edu_years', 'prior_earn'],
    distance='propensity', method='nearest',
    n_matches=3, caliper=0.2
)
match_result

/var/folders/bm/2cq1vtmd5wg6k0vdjfpvbmww0000gn/T/ipykernel_15847/717465332.py:3: UserWarning: PSM can increase imbalance and bias (King & Nielsen 2019). Consider distance='mahalanobis' or method='cem'.
  match_result = sp.match(

In [17]:
# 绘图：Love 图（匹配前后协变量平衡性）
# Plot: Love plot (covariate balance before/after matching)
fig, ax = sp.balanceplot(match_result, title='Covariate Balance: Love Plot')
sp.interactive(fig)

HBox(children=(VBox(children=(Image(value=b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x03\x12\x00\x00\x01\x8…

FigureEditor(fig=<Figure size 1200x600 with 1 Axes>, protect_data=True, edits=[], artist_roles={5283373712: <ArtistRole.LABEL: 5>, 5283853904: <ArtistRole.LABEL: 5>, 5283099216: <ArtistRole.LABEL: 5>, 5283487504: <ArtistRole.SPINE: 8>, 5282663248: <ArtistRole.SPINE: 8>, 5282961680: <ArtistRole.SPINE: 8>, 5282966608: <ArtistRole.SPINE: 8>, 5283995088: <ArtistRole.REFERENCE: 4>, 5283410128: <ArtistRole.REFERENCE: 4>, 5283187408: <ArtistRole.REFERENCE: 4>, 5283035344: <ArtistRole.DATA: 1>, 5283401616: <ArtistRole.COSMETIC: 9>, 5283811216: <ArtistRole.COSMETIC: 9>, 5283404816: <ArtistRole.COSMETIC: 9>, 5284094416: <ArtistRole.COSMETIC: 9>}, _original_state={'ax.title.text': 'Covariate Balance: Love Plot', 'ax.title.fontsize': 13.0, 'ax.title.color': 'black', 'ax.title.fontweight': 'normal', 'ax.xlabel.text': 'Standardized Mean Difference (SMD)', 'ax.xlabel.fontsize': 11.0, 'ax.xlabel.color': 'black', 'ax.ylabel.text': '', 'ax.ylabel.fontsize': 11.0, 'ax.ylabel.color': 'black', 'ax.xlim': (np.float64(-0.31018), np.float64(0.6265799999999999)), 'ax.ylim': (np.float64(3.1610000000000005), np.float64(-0.16100000000000003)), 'ax.facecolor': (1.0, 1.0, 1.0, 1.0), 'ax.xtick_rotation': 0.0, 'ax.ytick_rotation': 0.0, 'ax.spines.left.visible': True, 'ax.spines.right.visible': False, 'ax.spines.bottom.visible': True, 'ax.spines.top.visible': False, 'ax.grid': False, 'ax.line0.color': '#E74C3C', 'ax.line0.linewidth': 0.8, 'ax.line0.linestyle': '--', 'ax.line0.alpha': 0.5, 'ax.line0.marker': 'None', 'ax.line1.color': '#E74C3C', 'ax.line1.linewidth': 0.8, 'ax.line1.linestyle': '--', 'ax.line1.alpha': 0.5, 'ax.line1.marker': 'None', 'ax.line2.color': 'gray', 'ax.line2.linewidth': 0.5, 'ax.line2.linestyle': '-', 'ax.line2.alpha': None, 'ax.line2.marker': 'None', 'ax.coll0.alpha': None, 'ax.coll0.facecolors': array([[0.90588235, 0.29803922, 0.23529412, 1.        ],
       [0.90588235, 0.29803922, 0.23529412, 1.        ],
       [0.90588235, 0.29803922, 0.23529412, 1.        ],
       [0.90588235, 0.29803922, 0.23529412, 1.        ]]), 'ax.n_texts': 0, 'fig.figsize': (np.float64(8.0), np.float64(4.0)), 'fig.dpi': 150.0, 'fig.facecolor': (1.0, 1.0, 1.0, 1.0)}, _on_refresh_callbacks=[<function create_jupyter_panel.<locals>._live_refresh at 0x13ae95c60>, <function create_jupyter_panel.<locals>._live_history_update at 0x13b0a4860>, <function create_jupyter_panel.<locals>._live_code_update at 0x13b0a5800>], _redo_stack=[])

In [18]:
# 绘图：倾向得分分布（共同支撑域）
# Plot: Propensity score distribution (common support)
fig, ax = sp.psplot(
    df_match, treat='treatment',
    covariates=['age', 'edu_years', 'prior_earn'],
    title='Propensity Score Distribution',
    colors=('#3498DB', '#E74C3C'),
    labels=('Control Group', 'Training Program'),
)
sp.interactive(fig)

HBox(children=(VBox(children=(Image(value=b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x03\x12\x00\x00\x01\xe…

FigureEditor(fig=<Figure size 1200x750 with 1 Axes>, protect_data=True, edits=[], artist_roles={5285065936: <ArtistRole.LABEL: 5>, 5283028688: <ArtistRole.LABEL: 5>, 5284472080: <ArtistRole.LABEL: 5>, 5284618896: <ArtistRole.SPINE: 8>, 5284618064: <ArtistRole.SPINE: 8>, 5283278032: <ArtistRole.SPINE: 8>, 5284404560: <ArtistRole.SPINE: 8>, 5284944336: <ArtistRole.LEGEND: 7>, 5284143696: <ArtistRole.COSMETIC: 9>, 5284530960: <ArtistRole.COSMETIC: 9>, 5285720080: <ArtistRole.COSMETIC: 9>, 5098868944: <ArtistRole.COSMETIC: 9>, 5284692496: <ArtistRole.COSMETIC: 9>, 5284695056: <ArtistRole.COSMETIC: 9>, 5284697808: <ArtistRole.COSMETIC: 9>, 5284700368: <ArtistRole.COSMETIC: 9>, 5284692432: <ArtistRole.COSMETIC: 9>, 5284694992: <ArtistRole.COSMETIC: 9>, 5284707408: <ArtistRole.COSMETIC: 9>, 5285693008: <ArtistRole.COSMETIC: 9>, 5285695376: <ArtistRole.COSMETIC: 9>, 5285697936: <ArtistRole.COSMETIC: 9>, 5285700240: <ArtistRole.COSMETIC: 9>, 5283803152: <ArtistRole.COSMETIC: 9>, 5285704912: <ArtistRole.COSMETIC: 9>, 5285707152: <ArtistRole.COSMETIC: 9>, 5285447376: <ArtistRole.COSMETIC: 9>, 5285449808: <ArtistRole.COSMETIC: 9>, 5284699472: <ArtistRole.COSMETIC: 9>, 5284701456: <ArtistRole.COSMETIC: 9>, 5285456848: <ArtistRole.COSMETIC: 9>, 5285459024: <ArtistRole.COSMETIC: 9>, 5285461584: <ArtistRole.COSMETIC: 9>, 5284972560: <ArtistRole.COSMETIC: 9>, 5284974864: <ArtistRole.COSMETIC: 9>, 5283993744: <ArtistRole.COSMETIC: 9>, 5285701328: <ArtistRole.COSMETIC: 9>, 5285704080: <ArtistRole.COSMETIC: 9>, 5284984464: <ArtistRole.COSMETIC: 9>, 5284986832: <ArtistRole.COSMETIC: 9>, 5285742736: <ArtistRole.COSMETIC: 9>, 5285515664: <ArtistRole.COSMETIC: 9>, 5285453648: <ArtistRole.COSMETIC: 9>, 5284702096: <ArtistRole.COSMETIC: 9>, 5285720336: <ArtistRole.COSMETIC: 9>, 5285230608: <ArtistRole.COSMETIC: 9>, 5285756496: <ArtistRole.COSMETIC: 9>, 5285448464: <ArtistRole.COSMETIC: 9>, 5284976464: <ArtistRole.COSMETIC: 9>, 5285799632: <ArtistRole.COSMETIC: 9>, 5285459280: <ArtistRole.COSMETIC: 9>, 5284985552: <ArtistRole.COSMETIC: 9>, 5285839440: <ArtistRole.COSMETIC: 9>, 5285841744: <ArtistRole.COSMETIC: 9>, 5284698512: <ArtistRole.COSMETIC: 9>, 5285846544: <ArtistRole.COSMETIC: 9>, 5285839376: <ArtistRole.COSMETIC: 9>, 5285192464: <ArtistRole.COSMETIC: 9>, 5285723152: <ArtistRole.COSMETIC: 9>, 5285855056: <ArtistRole.COSMETIC: 9>, 5285318608: <ArtistRole.COSMETIC: 9>, 5285318800: <ArtistRole.COSMETIC: 9>, 5285911504: <ArtistRole.COSMETIC: 9>, 5285913936: <ArtistRole.COSMETIC: 9>, 5285916304: <ArtistRole.COSMETIC: 9>, 5285230672: <ArtistRole.COSMETIC: 9>, 5285920592: <ArtistRole.COSMETIC: 9>, 5285055248: <ArtistRole.COSMETIC: 9>, 5285941712: <ArtistRole.COSMETIC: 9>, 5285943760: <ArtistRole.COSMETIC: 9>, 5284898640: <ArtistRole.COSMETIC: 9>, 5284703824: <ArtistRole.COSMETIC: 9>, 5285656848: <ArtistRole.COSMETIC: 9>, 5285953040: <ArtistRole.COSMETIC: 9>, 5286020944: <ArtistRole.COSMETIC: 9>, 5285794704: <ArtistRole.COSMETIC: 9>, 5285535376: <ArtistRole.COSMETIC: 9>, 5285436368: <ArtistRole.COSMETIC: 9>, 5285721168: <ArtistRole.COSMETIC: 9>, 5286032912: <ArtistRole.COSMETIC: 9>, 5286035280: <ArtistRole.COSMETIC: 9>, 5285940368: <ArtistRole.COSMETIC: 9>, 5286072528: <ArtistRole.COSMETIC: 9>, 5286074704: <ArtistRole.COSMETIC: 9>, 5285947216: <ArtistRole.COSMETIC: 9>, 5285916560: <ArtistRole.COSMETIC: 9>, 5285918800: <ArtistRole.COSMETIC: 9>, 5286083792: <ArtistRole.COSMETIC: 9>}, _original_state={'ax.title.text': 'Propensity Score Distribution', 'ax.title.fontsize': 13.0, 'ax.title.color': 'black', 'ax.title.fontweight': 'normal', 'ax.xlabel.text': 'Propensity Score', 'ax.xlabel.fontsize': 11.0, 'ax.xlabel.color': 'black', 'ax.ylabel.text': 'Density', 'ax.ylabel.fontsize': 11.0, 'ax.ylabel.color': 'black', 'ax.xlim': (np.float64(-0.02), np.float64(1.02)), 'ax.ylim': (np.float64(0.0), np.float64(3.9835051546391718)), 'ax.facecolor': (1.0, 1.0, 1.0, 1.0), 'ax.xtick_rotation': 0.0, 'ax.ytick_rotation': 0.0, 'ax.spines.left.visible': True, 'ax.spines.right.visible': False, 'ax.spines.bottom.visible': True, 'ax.spines.top.visible': False, 'ax.grid': False, 'ax.n_texts': 0, 'fig.figsize': (np.float64(8.0), np.float64(5.0)), 'fig.dpi': 150.0, 'fig.facecolor': (1.0, 1.0, 1.0, 1.0)}, _on_refresh_callbacks=[<function create_jupyter_panel.<locals>._live_refresh at 0x13b13bc40>, <function create_jupyter_panel.<locals>._live_history_update at 0x13b259c60>, <function create_jupyter_panel.<locals>._live_code_update at 0x13b25ac00>], _redo_stack=[])

---
## 5. Synthetic Control (SC)

A policy intervention in State 1 starting in year 2005. 10 donor states.

---
## 5. 合成控制法 (SC)

州 1 在 2005 年实施政策干预，使用 10 个捐赠州构建合成控制。

In [19]:
# 模拟合成控制数据：11 个州，20 个时期
# Simulate synthetic control data
n_states, n_periods = 11, 20
states = np.repeat(np.arange(1, n_states + 1), n_periods)
time_periods = np.tile(np.arange(2000, 2000 + n_periods), n_states)

# Each state has a base trend + state-specific intercept
state_intercepts = np.repeat(np.random.normal(50, 5, n_states), n_periods)
common_trend = np.tile(np.linspace(0, 10, n_periods), n_states)
noise = np.random.normal(0, 1, n_states * n_periods)

gdp = state_intercepts + common_trend + noise

# Add treatment effect for state 1 after 2005 (effect = +5)
treatment_effect = 5.0 * ((states == 1) & (time_periods >= 2005)).astype(float)
gdp += treatment_effect

df_synth = pd.DataFrame({
    'state': states, 'year': time_periods, 'gdp': gdp
})
df_synth.head()

   state  year        gdp
0      1  2000  47.983380
1      1  2001  49.634079
2      1  2002  48.875418
3      1  2003  50.008466
4      1  2004  49.088300

In [20]:
# 经典合成控制法
# Classic Synthetic Control
sc_result = sp.synth(
    df_synth,
    outcome='gdp', unit='state', time='year',
    treated_unit=1, treatment_time=2005
)
sc_result

In [21]:
# 绘图：处理单元 vs 合成控制轨迹
# Plot: Treated vs Synthetic trajectory
fig, ax = sp.synthplot(sc_result, type='trajectory',
                       title='Synthetic Control: State 1 vs Synthetic')
sp.interactive(fig)

HBox(children=(VBox(children=(Image(value=b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x03\xda\x00\x00\x02{\x…

FigureEditor(fig=<Figure size 1500x975 with 1 Axes>, protect_data=True, edits=[], artist_roles={5287207824: <ArtistRole.LABEL: 5>, 5286622800: <ArtistRole.LABEL: 5>, 5287458192: <ArtistRole.LABEL: 5>, 5286568144: <ArtistRole.SPINE: 8>, 5287232976: <ArtistRole.SPINE: 8>, 5287337104: <ArtistRole.SPINE: 8>, 5287331152: <ArtistRole.SPINE: 8>, 5285796240: <ArtistRole.LEGEND: 7>, 5285522960: <ArtistRole.DATA: 1>, 5286738128: <ArtistRole.DATA: 1>, 5286462864: <ArtistRole.REFERENCE: 4>, 5287150800: <ArtistRole.CI: 3>}, _original_state={'ax.title.text': 'Synthetic Control: State 1 vs Synthetic', 'ax.title.fontsize': 13.0, 'ax.title.color': 'black', 'ax.title.fontweight': 'normal', 'ax.xlabel.text': 'Time', 'ax.xlabel.fontsize': 11.0, 'ax.xlabel.color': 'black', 'ax.ylabel.text': 'Outcome', 'ax.ylabel.fontsize': 11.0, 'ax.ylabel.color': 'black', 'ax.xlim': (np.float64(1999.05), np.float64(2019.95)), 'ax.ylim': (np.float64(47.12487078585494), np.float64(66.01208356282729)), 'ax.facecolor': (1.0, 1.0, 1.0, 1.0), 'ax.xtick_rotation': 0.0, 'ax.ytick_rotation': 0.0, 'ax.spines.left.visible': True, 'ax.spines.right.visible': False, 'ax.spines.bottom.visible': True, 'ax.spines.top.visible': False, 'ax.grid': False, 'ax.line0.color': '#2C3E50', 'ax.line0.linewidth': 2.2, 'ax.line0.linestyle': '-', 'ax.line0.alpha': None, 'ax.line0.marker': 'None', 'ax.line1.color': '#E74C3C', 'ax.line1.linewidth': 2.2, 'ax.line1.linestyle': '--', 'ax.line1.alpha': None, 'ax.line1.marker': 'None', 'ax.line2.color': '#95A5A6', 'ax.line2.linewidth': 1.2, 'ax.line2.linestyle': ':', 'ax.line2.alpha': 0.8, 'ax.line2.marker': 'None', 'ax.coll0.alpha': 0.12, 'ax.coll0.facecolors': array([[0.90588235, 0.29803922, 0.23529412, 0.12      ]]), 'ax.n_texts': 0, 'fig.figsize': (np.float64(10.0), np.float64(6.5)), 'fig.dpi': 150.0, 'fig.facecolor': (1.0, 1.0, 1.0, 1.0)}, _on_refresh_callbacks=[<function create_jupyter_panel.<locals>._live_refresh at 0x13b2a3420>, <function create_jupyter_panel.<locals>._live_history_update at 0x13b3c18a0>, <function create_jupyter_panel.<locals>._live_code_update at 0x13b3c2840>], _redo_stack=[])

In [22]:
# 绘图：处理效应差距随时间变化
# Plot: Treatment effect gap over time
fig, ax = sp.synthplot(sc_result, type='gap',
                       title='SC: Treatment Effect Gap (Treated - Synthetic)')
sp.interactive(fig)

HBox(children=(VBox(children=(Image(value=b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x03\xda\x00\x00\x01\xe…

FigureEditor(fig=<Figure size 1500x750 with 1 Axes>, protect_data=True, edits=[], artist_roles={5288567568: <ArtistRole.LABEL: 5>, 5288395280: <ArtistRole.LABEL: 5>, 5288365392: <ArtistRole.LABEL: 5>, 5288490320: <ArtistRole.SPINE: 8>, 5288484944: <ArtistRole.SPINE: 8>, 5287573712: <ArtistRole.SPINE: 8>, 5288404304: <ArtistRole.SPINE: 8>, 5288814928: <ArtistRole.DATA: 1>, 5287848400: <ArtistRole.REFERENCE: 4>, 5288610832: <ArtistRole.REFERENCE: 4>, 5288297680: <ArtistRole.CI: 3>}, _original_state={'ax.title.text': 'SC: Treatment Effect Gap (Treated - Synthetic)', 'ax.title.fontsize': 13.0, 'ax.title.color': 'black', 'ax.title.fontweight': 'normal', 'ax.xlabel.text': 'Time', 'ax.xlabel.fontsize': 11.0, 'ax.xlabel.color': 'black', 'ax.ylabel.text': 'Gap (Treated − Synthetic)', 'ax.ylabel.fontsize': 11.0, 'ax.ylabel.color': 'black', 'ax.xlim': (np.float64(1999.05), np.float64(2019.95)), 'ax.ylim': (np.float64(-1.1744815757430636), np.float64(8.016774002802455)), 'ax.facecolor': (1.0, 1.0, 1.0, 1.0), 'ax.xtick_rotation': 0.0, 'ax.ytick_rotation': 0.0, 'ax.spines.left.visible': True, 'ax.spines.right.visible': False, 'ax.spines.bottom.visible': True, 'ax.spines.top.visible': False, 'ax.grid': False, 'ax.line0.color': '#2C3E50', 'ax.line0.linewidth': 2.0, 'ax.line0.linestyle': '-', 'ax.line0.alpha': None, 'ax.line0.marker': 'None', 'ax.line1.color': 'gray', 'ax.line1.linewidth': 0.8, 'ax.line1.linestyle': '--', 'ax.line1.alpha': None, 'ax.line1.marker': 'None', 'ax.line2.color': '#95A5A6', 'ax.line2.linewidth': 1.2, 'ax.line2.linestyle': ':', 'ax.line2.alpha': 0.8, 'ax.line2.marker': 'None', 'ax.coll0.alpha': 0.12, 'ax.coll0.facecolors': array([[0.20392157, 0.59607843, 0.85882353, 0.12      ]]), 'ax.n_texts': 0, 'fig.figsize': (np.float64(10.0), np.float64(5.0)), 'fig.dpi': 150.0, 'fig.facecolor': (1.0, 1.0, 1.0, 1.0)}, _on_refresh_callbacks=[<function create_jupyter_panel.<locals>._live_refresh at 0x13b3d4f40>, <function create_jupyter_panel.<locals>._live_history_update at 0x13b461a80>, <function create_jupyter_panel.<locals>._live_code_update at 0x13b463ce0>], _redo_stack=[])

In [23]:
# 绘图：捐赠州权重
# Plot: Donor weights
fig, ax = sp.synthplot(sc_result, type='weights',
                       title='SC: Donor State Weights')
sp.interactive(fig)

HBox(children=(VBox(children=(Image(value=b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x03\x13\x00\x00\x01\xe…

FigureEditor(fig=<Figure size 1200x750 with 1 Axes>, protect_data=True, edits=[], artist_roles={5289344784: <ArtistRole.LABEL: 5>, 5289670224: <ArtistRole.LABEL: 5>, 5290024976: <ArtistRole.LABEL: 5>, 5289336592: <ArtistRole.SPINE: 8>, 5289202896: <ArtistRole.SPINE: 8>, 5289633360: <ArtistRole.SPINE: 8>, 5289712656: <ArtistRole.SPINE: 8>, 5289351952: <ArtistRole.REFERENCE: 4>, 5290120912: <ArtistRole.COSMETIC: 9>, 5289486352: <ArtistRole.COSMETIC: 9>, 5289845520: <ArtistRole.COSMETIC: 9>, 5290169552: <ArtistRole.COSMETIC: 9>}, _original_state={'ax.title.text': 'SC: Donor State Weights', 'ax.title.fontsize': 13.0, 'ax.title.color': 'black', 'ax.title.fontweight': 'normal', 'ax.xlabel.text': 'Weight', 'ax.xlabel.fontsize': 11.0, 'ax.xlabel.color': 'black', 'ax.ylabel.text': '', 'ax.ylabel.fontsize': 11.0, 'ax.ylabel.color': 'black', 'ax.xlim': (np.float64(0.0), np.float64(0.4642936592746817)), 'ax.ylim': (np.float64(-0.5900000000000001), np.float64(3.5900000000000003)), 'ax.facecolor': (1.0, 1.0, 1.0, 1.0), 'ax.xtick_rotation': 0.0, 'ax.ytick_rotation': 0.0, 'ax.spines.left.visible': True, 'ax.spines.right.visible': False, 'ax.spines.bottom.visible': True, 'ax.spines.top.visible': False, 'ax.grid': False, 'ax.line0.color': 'gray', 'ax.line0.linewidth': 0.5, 'ax.line0.linestyle': '-', 'ax.line0.alpha': None, 'ax.line0.marker': 'None', 'ax.n_texts': 0, 'fig.figsize': (np.float64(8.0), np.float64(5.0)), 'fig.dpi': 150.0, 'fig.facecolor': (1.0, 1.0, 1.0, 1.0)}, _on_refresh_callbacks=[<function create_jupyter_panel.<locals>._live_refresh at 0x13b51e3e0>, <function create_jupyter_panel.<locals>._live_history_update at 0x13b5efd80>, <function create_jupyter_panel.<locals>._live_code_update at 0x13c248d60>], _redo_stack=[])

In [24]:
# 绘图：安慰剂检验（空间维度）
# Plot: Placebo test (in-space)
fig, ax = sp.synthplot(sc_result, type='placebo',
                       title='SC: In-Space Placebo Test')
sp.interactive(fig)

HBox(children=(VBox(children=(Image(value=b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x03q\x00\x00\x02I\x08\…

FigureEditor(fig=<Figure size 1350x900 with 1 Axes>, protect_data=True, edits=[], artist_roles={5290630352: <ArtistRole.LABEL: 5>, 5290909648: <ArtistRole.LABEL: 5>, 5290899792: <ArtistRole.LABEL: 5>, 5291064848: <ArtistRole.SPINE: 8>, 5291056336: <ArtistRole.SPINE: 8>, 5290222864: <ArtistRole.SPINE: 8>, 5290910352: <ArtistRole.SPINE: 8>, 5289630160: <ArtistRole.LEGEND: 7>, 5287871824: <ArtistRole.REFERENCE: 4>, 5290289296: <ArtistRole.ANNOTATION: 6>, 5283434576: <ArtistRole.COSMETIC: 9>, 5304101008: <ArtistRole.COSMETIC: 9>, 5304201424: <ArtistRole.COSMETIC: 9>, 5304203792: <ArtistRole.COSMETIC: 9>, 5304009488: <ArtistRole.COSMETIC: 9>, 5304011984: <ArtistRole.COSMETIC: 9>, 5304014864: <ArtistRole.COSMETIC: 9>, 5304017232: <ArtistRole.COSMETIC: 9>}, _original_state={'ax.title.text': 'SC: In-Space Placebo Test', 'ax.title.fontsize': 13.0, 'ax.title.color': 'black', 'ax.title.fontweight': 'normal', 'ax.xlabel.text': 'ATT', 'ax.xlabel.fontsize': 11.0, 'ax.xlabel.color': 'black', 'ax.ylabel.text': 'Count', 'ax.ylabel.fontsize': 11.0, 'ax.ylabel.color': 'black', 'ax.xlim': (np.float64(-4.01669418127356), np.float64(6.095566070673677)), 'ax.ylim': (np.float64(0.0), np.float64(3.15)), 'ax.facecolor': (1.0, 1.0, 1.0, 1.0), 'ax.xtick_rotation': 0.0, 'ax.ytick_rotation': 0.0, 'ax.spines.left.visible': True, 'ax.spines.right.visible': False, 'ax.spines.bottom.visible': True, 'ax.spines.top.visible': False, 'ax.grid': False, 'ax.line0.color': '#E74C3C', 'ax.line0.linewidth': 2.5, 'ax.line0.linestyle': '--', 'ax.line0.alpha': None, 'ax.line0.marker': 'None', 'ax.n_texts': 1, 'fig.figsize': (np.float64(9.0), np.float64(6.0)), 'fig.dpi': 150.0, 'fig.facecolor': (1.0, 1.0, 1.0, 1.0)}, _on_refresh_callbacks=[<function create_jupyter_panel.<locals>._live_refresh at 0x13c26fce0>, <function create_jupyter_panel.<locals>._live_history_update at 0x13c382020>, <function create_jupyter_panel.<locals>._live_code_update at 0x13b5ef7e0>], _redo_stack=[])

---
## 6. Regression Discontinuity Design (RDD)

Scholarship eligibility based on a test score cutoff at 60.

---
## 6. 断点回归设计 (RDD)

基于考试分数 60 分断点的奖学金资格评估。

In [25]:
# 模拟 RDD 数据：分数断点在 60 分
# Simulate RDD data
n_rd = 2000
score = np.random.normal(60, 15, n_rd)  # running variable, cutoff at 60
above_cutoff = (score >= 60).astype(int)

# Outcome: GPA with a jump at the cutoff (treatment effect = 0.4)
gpa = 2.5 + 0.02 * score + 0.4 * above_cutoff + np.random.normal(0, 0.3, n_rd)

df_rd = pd.DataFrame({
    'gpa': gpa, 'test_score': score, 'scholarship': above_cutoff
})
df_rd.head()

        gpa  test_score  scholarship
0  4.704528   79.379964            1
1  3.760986   53.293551            0
2  4.232309   83.322604            1
3  4.320970   62.941639            1
4  4.392721   90.379263            1

In [26]:
# 精确断点回归估计
# Sharp RD estimation
rd_result = sp.rdrobust(
    df_rd, y='gpa', x='test_score', c=60
)
rd_result

In [27]:
# 绘图：RD 散点图（含多项式拟合和置信区间阴影）
# Plot: RD scatter with polynomial fit and CI shading
fig, ax = sp.rdplot(
    df_rd, y='gpa', x='test_score', c=60,
    nbins=40, ci_level=0.95, shade_ci=True,
    show_bw=True,
    title='RDD: Scholarship Effect on GPA',
)
sp.interactive(fig)

HBox(children=(VBox(children=(Image(value=b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x03\xda\x00\x00\x02\xa…

FigureEditor(fig=<Figure size 1500x1050 with 1 Axes>, protect_data=True, edits=[], artist_roles={5305302800: <ArtistRole.LABEL: 5>, 5304055376: <ArtistRole.LABEL: 5>, 5304807440: <ArtistRole.LABEL: 5>, 5304833488: <ArtistRole.SPINE: 8>, 5305089040: <ArtistRole.SPINE: 8>, 5305080208: <ArtistRole.SPINE: 8>, 5290330960: <ArtistRole.SPINE: 8>, 5304753360: <ArtistRole.LEGEND: 7>, 5305561872: <ArtistRole.DATA: 1>, 5305564880: <ArtistRole.DATA: 1>, 5305563024: <ArtistRole.REFERENCE: 4>, 5305542288: <ArtistRole.CI: 3>, 5303877904: <ArtistRole.CI: 3>, 5304934288: <ArtistRole.DATA: 1>, 5305556880: <ArtistRole.DATA: 1>, 5304627984: <ArtistRole.COSMETIC: 9>}, _original_state={'ax.title.text': 'RDD: Scholarship Effect on GPA', 'ax.title.fontsize': 13.0, 'ax.title.color': 'black', 'ax.title.fontweight': 'normal', 'ax.xlabel.text': 'test_score', 'ax.xlabel.fontsize': 11.0, 'ax.xlabel.color': 'black', 'ax.ylabel.text': 'gpa', 'ax.ylabel.fontsize': 11.0, 'ax.ylabel.color': 'black', 'ax.xlim': (np.float64(0.07987285086862705), np.float64(112.14412014740388)), 'ax.ylim': (np.float64(1.2854934394387991), np.float64(5.256102374147356)), 'ax.facecolor': (1.0, 1.0, 1.0, 1.0), 'ax.xtick_rotation': 0.0, 'ax.ytick_rotation': 0.0, 'ax.spines.left.visible': True, 'ax.spines.right.visible': False, 'ax.spines.bottom.visible': True, 'ax.spines.top.visible': False, 'ax.grid': False, 'ax.line0.color': '#E74C3C', 'ax.line0.linewidth': 1.5, 'ax.line0.linestyle': '-', 'ax.line0.alpha': None, 'ax.line0.marker': 'None', 'ax.line1.color': '#3498DB', 'ax.line1.linewidth': 1.5, 'ax.line1.linestyle': '-', 'ax.line1.alpha': None, 'ax.line1.marker': 'None', 'ax.line2.color': 'gray', 'ax.line2.linewidth': 0.8, 'ax.line2.linestyle': '--', 'ax.line2.alpha': 0.7, 'ax.line2.marker': 'None', 'ax.coll0.alpha': 0.12, 'ax.coll0.facecolors': array([[0.90588235, 0.29803922, 0.23529412, 0.12      ]]), 'ax.coll1.alpha': 0.12, 'ax.coll1.facecolors': array([[0.20392157, 0.59607843, 0.85882353, 0.12      ]]), 'ax.coll2.alpha': 0.8, 'ax.coll2.facecolors': array([[0.17254902, 0.24313725, 0.31372549, 0.8       ]]), 'ax.coll3.alpha': 0.8, 'ax.coll3.facecolors': array([[0.17254902, 0.24313725, 0.31372549, 0.8       ]]), 'ax.n_texts': 0, 'fig.figsize': (np.float64(10.0), np.float64(7.0)), 'fig.dpi': 150.0, 'fig.facecolor': (1.0, 1.0, 1.0, 1.0)}, _on_refresh_callbacks=[<function create_jupyter_panel.<locals>._live_refresh at 0x13c408360>, <function create_jupyter_panel.<locals>._live_history_update at 0x13c4d68e0>, <function create_jupyter_panel.<locals>._live_code_update at 0x13c4d7880>], _redo_stack=[])

In [28]:
# 绘图：密度检验（McCrary 式）— 检查是否存在操纵
# Plot: Density test (McCrary-style) — check for manipulation
fig, ax = sp.rdplotdensity(
    df_rd, x='test_score', c=60,
    hist=True, nbins=40, ci_level=0.95,
    title='RDD: Running Variable Density at Cutoff',
)
sp.interactive(fig)

HBox(children=(VBox(children=(Image(value=b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x03\xda\x00\x00\x02\xa…

FigureEditor(fig=<Figure size 1500x1050 with 1 Axes>, protect_data=True, edits=[], artist_roles={5305454544: <ArtistRole.LABEL: 5>, 5306121744: <ArtistRole.LABEL: 5>, 5306106256: <ArtistRole.LABEL: 5>, 5306237072: <ArtistRole.SPINE: 8>, 5306219664: <ArtistRole.SPINE: 8>, 5306212240: <ArtistRole.SPINE: 8>, 5306206416: <ArtistRole.SPINE: 8>, 5307361744: <ArtistRole.LEGEND: 7>, 5307208400: <ArtistRole.REFERENCE: 4>, 5307521168: <ArtistRole.REFERENCE: 4>, 5290412880: <ArtistRole.REFERENCE: 4>, 5307521616: <ArtistRole.CI: 3>, 5307527248: <ArtistRole.CI: 3>, 5306514512: <ArtistRole.COSMETIC: 9>, 5305995152: <ArtistRole.COSMETIC: 9>, 5306763472: <ArtistRole.COSMETIC: 9>, 5290837840: <ArtistRole.COSMETIC: 9>, 5306768080: <ArtistRole.COSMETIC: 9>, 5306770512: <ArtistRole.COSMETIC: 9>, 5306562320: <ArtistRole.COSMETIC: 9>, 5305946960: <ArtistRole.COSMETIC: 9>, 5306768016: <ArtistRole.COSMETIC: 9>, 5306770448: <ArtistRole.COSMETIC: 9>, 5307027920: <ArtistRole.COSMETIC: 9>, 5306769360: <ArtistRole.COSMETIC: 9>, 5306344592: <ArtistRole.COSMETIC: 9>, 5307036112: <ArtistRole.COSMETIC: 9>, 5306448144: <ArtistRole.COSMETIC: 9>, 5306351376: <ArtistRole.COSMETIC: 9>, 5306976400: <ArtistRole.COSMETIC: 9>, 5306896784: <ArtistRole.COSMETIC: 9>, 5306654160: <ArtistRole.COSMETIC: 9>, 5306983504: <ArtistRole.COSMETIC: 9>, 5306067728: <ArtistRole.COSMETIC: 9>, 5306988176: <ArtistRole.COSMETIC: 9>, 5306990480: <ArtistRole.COSMETIC: 9>, 5307090960: <ArtistRole.COSMETIC: 9>, 5307093328: <ArtistRole.COSMETIC: 9>, 5306931344: <ArtistRole.COSMETIC: 9>, 5306343888: <ArtistRole.COSMETIC: 9>, 5307100368: <ArtistRole.COSMETIC: 9>, 5307102736: <ArtistRole.COSMETIC: 9>, 5307104912: <ArtistRole.COSMETIC: 9>, 5306977936: <ArtistRole.COSMETIC: 9>, 5306979472: <ArtistRole.COSMETIC: 9>, 5307144464: <ArtistRole.COSMETIC: 9>, 5307146832: <ArtistRole.COSMETIC: 9>, 5306986512: <ArtistRole.COSMETIC: 9>, 5307151440: <ArtistRole.COSMETIC: 9>, 5307153936: <ArtistRole.COSMETIC: 9>, 5306976656: <ArtistRole.COSMETIC: 9>, 5307207696: <ArtistRole.COSMETIC: 9>, 5307145552: <ArtistRole.COSMETIC: 9>, 5307209488: <ArtistRole.COSMETIC: 9>, 5307215952: <ArtistRole.COSMETIC: 9>, 5307218640: <ArtistRole.COSMETIC: 9>, 5307253968: <ArtistRole.COSMETIC: 9>, 5307256080: <ArtistRole.COSMETIC: 9>, 5307258704: <ArtistRole.COSMETIC: 9>, 5307261136: <ArtistRole.COSMETIC: 9>, 5305953872: <ArtistRole.COSMETIC: 9>, 5307256016: <ArtistRole.COSMETIC: 9>, 5307095120: <ArtistRole.COSMETIC: 9>, 5306974736: <ArtistRole.COSMETIC: 9>, 5307305296: <ArtistRole.COSMETIC: 9>, 5307307664: <ArtistRole.COSMETIC: 9>, 5307212816: <ArtistRole.COSMETIC: 9>, 5307260432: <ArtistRole.COSMETIC: 9>, 5307314704: <ArtistRole.COSMETIC: 9>, 5306367824: <ArtistRole.COSMETIC: 9>, 5305714896: <ArtistRole.COSMETIC: 9>, 5307027856: <ArtistRole.COSMETIC: 9>, 5306931472: <ArtistRole.COSMETIC: 9>, 5305996560: <ArtistRole.COSMETIC: 9>, 5306411472: <ArtistRole.COSMETIC: 9>, 5307036688: <ArtistRole.COSMETIC: 9>, 5307365392: <ArtistRole.COSMETIC: 9>, 5306647504: <ArtistRole.COSMETIC: 9>, 5307355536: <ArtistRole.COSMETIC: 9>, 5307357840: <ArtistRole.COSMETIC: 9>, 5306213200: <ArtistRole.COSMETIC: 9>, 5307426704: <ArtistRole.COSMETIC: 9>, 5306347984: <ArtistRole.COSMETIC: 9>, 5306415184: <ArtistRole.COSMETIC: 9>, 5307450064: <ArtistRole.COSMETIC: 9>, 5307027152: <ArtistRole.COSMETIC: 9>, 5306341392: <ArtistRole.COSMETIC: 9>, 5307097424: <ArtistRole.COSMETIC: 9>, 5307459024: <ArtistRole.COSMETIC: 9>, 5306774224: <ArtistRole.COSMETIC: 9>, 5306514640: <ArtistRole.COSMETIC: 9>, 5307465552: <ArtistRole.COSMETIC: 9>, 5307517200: <ArtistRole.COSMETIC: 9>}, _original_state={'ax.title.text': 'RDD: Running Variable Density at Cutoff', 'ax.title.fontsize': 13.0, 'ax.title.color': 'black', 'ax.title.fontweight': 'normal', 'ax.xlabel.text': 'test_score', 'ax.xlabel.fontsize': 11.0, 'ax.xlabel.color': 'black', 'ax.ylabel.text': 'Density', 'ax.ylabel.fontsize': 11.0, 'ax.ylabel.color': 'black', 'ax.xlim': (np.float64(0.07987285086862705), np.float64(112.14412014740388)), 'ax.ylim': (np.float64(0.0), np.float64(0.06191045852950383)), 'ax.facecolor': (1.0, 1.0, 1.0, 1.0), 'ax.xtick_rotation': 0.0, 'ax.ytick_rotation': 0.0, 'ax.spines.left.visible': True, 'ax.spines.right.visible': False, 'ax.spines.bottom.visible': True, 'ax.spines.top.visible': False, 'ax.grid': False, 'ax.line0.color': '#E74C3C', 'ax.line0.linewidth': 2.0, 'ax.line0.linestyle': '-', 'ax.line0.alpha': None, 'ax.line0.marker': 'None', 'ax.line1.color': '#3498DB', 'ax.line1.linewidth': 2.0, 'ax.line1.linestyle': '-', 'ax.line1.alpha': None, 'ax.line1.marker': 'None', 'ax.line2.color': 'gray', 'ax.line2.linewidth': 1.0, 'ax.line2.linestyle': '--', 'ax.line2.alpha': 0.7, 'ax.line2.marker': 'None', 'ax.coll0.alpha': 0.15, 'ax.coll0.facecolors': array([[0.90588235, 0.29803922, 0.23529412, 0.15      ]]), 'ax.coll1.alpha': 0.15, 'ax.coll1.facecolors': array([[0.20392157, 0.59607843, 0.85882353, 0.15      ]]), 'ax.n_texts': 0, 'fig.figsize': (np.float64(10.0), np.float64(7.0)), 'fig.dpi': 150.0, 'fig.facecolor': (1.0, 1.0, 1.0, 1.0)}, _on_refresh_callbacks=[<function create_jupyter_panel.<locals>._live_refresh at 0x13c5f05e0>, <function create_jupyter_panel.<locals>._live_history_update at 0x13c6b2fc0>, <function create_jupyter_panel.<locals>._live_code_update at 0x13c6b3f60>], _redo_stack=[])

In [29]:
# 绘图：带宽敏感性 — 不同带宽下 RD 估计的稳健性
# Plot: Bandwidth sensitivity — RD estimate robustness across bandwidths
_ = sp.rdbwsensitivity(df_rd, y='gpa', x='test_score', c=60, n_grid=20)
fig = plt.gcf()
sp.interactive(fig)

HBox(children=(VBox(children=(Image(value=b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x03\xda\x00\x00\x02I\x…

FigureEditor(fig=<Figure size 1500x900 with 1 Axes>, protect_data=True, edits=[], artist_roles={5305437200: <ArtistRole.LABEL: 5>, 5308659280: <ArtistRole.LABEL: 5>, 5308004432: <ArtistRole.LABEL: 5>, 5308093776: <ArtistRole.SPINE: 8>, 5308339472: <ArtistRole.SPINE: 8>, 5308021840: <ArtistRole.SPINE: 8>, 5308015312: <ArtistRole.SPINE: 8>, 5308256080: <ArtistRole.LEGEND: 7>, 5308011344: <ArtistRole.DATA: 1>, 5307934736: <ArtistRole.REFERENCE: 4>, 5308124240: <ArtistRole.REFERENCE: 4>, 5308337360: <ArtistRole.REFERENCE: 4>, 5308714832: <ArtistRole.REFERENCE: 4>, 5308346640: <ArtistRole.CI: 3>}, _original_state={'ax.title.text': 'Bandwidth Sensitivity', 'ax.title.fontsize': 13.0, 'ax.title.color': 'black', 'ax.title.fontweight': 'normal', 'ax.xlabel.text': 'Bandwidth', 'ax.xlabel.fontsize': 11.0, 'ax.xlabel.color': 'black', 'ax.ylabel.text': 'RD Estimate', 'ax.ylabel.fontsize': 11.0, 'ax.ylabel.color': 'black', 'ax.xlim': (np.float64(1.274459825), np.float64(6.222362675)), 'ax.ylim': (np.float64(-0.034920611911106514), np.float64(0.7333328501332366)), 'ax.facecolor': (1.0, 1.0, 1.0, 1.0), 'ax.xtick_rotation': 0.0, 'ax.ytick_rotation': 0.0, 'ax.spines.left.visible': True, 'ax.spines.right.visible': False, 'ax.spines.bottom.visible': True, 'ax.spines.top.visible': False, 'ax.grid': False, 'ax.line0.color': '#2C3E50', 'ax.line0.linewidth': 1.0, 'ax.line0.linestyle': '-', 'ax.line0.alpha': 0.8, 'ax.line0.marker': 'o', 'ax.line1.color': '#2C3E50', 'ax.line1.linewidth': 1.0, 'ax.line1.linestyle': 'None', 'ax.line1.alpha': 0.8, 'ax.line1.marker': '_', 'ax.line2.color': '#2C3E50', 'ax.line2.linewidth': 1.0, 'ax.line2.linestyle': 'None', 'ax.line2.alpha': 0.8, 'ax.line2.marker': '_', 'ax.line3.color': 'gray', 'ax.line3.linewidth': 0.8, 'ax.line3.linestyle': '--', 'ax.line3.alpha': None, 'ax.line3.marker': 'None', 'ax.line4.color': '#E74C3C', 'ax.line4.linewidth': 0.8, 'ax.line4.linestyle': '--', 'ax.line4.alpha': 0.7, 'ax.line4.marker': 'None', 'ax.coll0.alpha': 0.8, 'ax.coll0.facecolors': array([], shape=(0, 4), dtype=float64), 'ax.n_texts': 0, 'fig.figsize': (np.float64(10.0), np.float64(6.0)), 'fig.dpi': 150.0, 'fig.facecolor': (1.0, 1.0, 1.0, 1.0)}, _on_refresh_callbacks=[<function create_jupyter_panel.<locals>._live_refresh at 0x13c748900>, <function create_jupyter_panel.<locals>._live_history_update at 0x13f692e80>, <function create_jupyter_panel.<locals>._live_code_update at 0x13f693e20>], _redo_stack=[])

---
## 7. Binscatter

Non-parametric conditional mean plots — the workhorse of applied micro visualization.

---
## 7. 分箱散点图 (Binscatter)

非参数条件均值图 —— 应用微观经济学可视化的常用工具。

In [30]:
# 分箱散点图：工资 vs 教育年限（来自 IV 数据），带置信区间
# Binscatter: wage vs education (from IV data) with CI bands
fig, ax, _ = sp.binscatter(
    df_iv, y='wage', x='education',
    n_bins=30, ci=True, ci_level=0.95,
    fit='linear',
    figsize=(9, 6),
)
ax.set_title('Binscatter: Wage vs Education', fontsize=13)
ax.set_xlabel('Years of Education', fontsize=11)
ax.set_ylabel('Hourly Wage ($)', fontsize=11)
sp.interactive(fig)

HBox(children=(VBox(children=(Image(value=b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x03v\x00\x00\x02_\x08\…

FigureEditor(fig=<Figure size 1350x900 with 1 Axes>, protect_data=True, edits=[], artist_roles={5309637712: <ArtistRole.LABEL: 5>, 5358997712: <ArtistRole.LABEL: 5>, 5358994000: <ArtistRole.LABEL: 5>, 5304454480: <ArtistRole.SPINE: 8>, 5309492688: <ArtistRole.SPINE: 8>, 5306108560: <ArtistRole.SPINE: 8>, 5307901008: <ArtistRole.SPINE: 8>, 5359150544: <ArtistRole.REFERENCE: 4>, 5307857808: <ArtistRole.REFERENCE: 4>, 5359224016: <ArtistRole.DATA: 1>, 5307936976: <ArtistRole.DATA: 1>, 5304318544: <ArtistRole.CI: 3>}, _original_state={'ax.title.text': 'Binscatter: Wage vs Education', 'ax.title.fontsize': 13.0, 'ax.title.color': 'black', 'ax.title.fontweight': 'normal', 'ax.xlabel.text': 'Years of Education', 'ax.xlabel.fontsize': 11.0, 'ax.xlabel.color': 'black', 'ax.ylabel.text': 'Hourly Wage ($)', 'ax.ylabel.fontsize': 11.0, 'ax.ylabel.color': 'black', 'ax.xlim': (np.float64(7.230837929080427), np.float64(16.794586435945824)), 'ax.ylim': (np.float64(17.30389032141836), np.float64(27.374847689259703)), 'ax.facecolor': (1.0, 1.0, 1.0, 1.0), 'ax.xtick_rotation': 0.0, 'ax.ytick_rotation': 0.0, 'ax.spines.left.visible': True, 'ax.spines.right.visible': False, 'ax.spines.bottom.visible': True, 'ax.spines.top.visible': False, 'ax.grid': False, 'ax.line0.color': '#2C3E50', 'ax.line0.linewidth': 0.8, 'ax.line0.linestyle': 'None', 'ax.line0.alpha': 0.6, 'ax.line0.marker': '_', 'ax.line1.color': '#2C3E50', 'ax.line1.linewidth': 0.8, 'ax.line1.linestyle': 'None', 'ax.line1.alpha': 0.6, 'ax.line1.marker': '_', 'ax.line2.color': '#2C3E50', 'ax.line2.linewidth': 1.5, 'ax.line2.linestyle': '-', 'ax.line2.alpha': 0.8, 'ax.line2.marker': 'None', 'ax.coll0.alpha': 0.85, 'ax.coll0.facecolors': array([[0.17254902, 0.24313725, 0.31372549, 0.85      ]]), 'ax.coll1.alpha': 0.6, 'ax.coll1.facecolors': array([], shape=(0, 4), dtype=float64), 'ax.n_texts': 0, 'fig.figsize': (np.float64(9.0), np.float64(6.0)), 'fig.dpi': 150.0, 'fig.facecolor': (1.0, 1.0, 1.0, 1.0)}, _on_refresh_callbacks=[<function create_jupyter_panel.<locals>._live_refresh at 0x13f6dade0>, <function create_jupyter_panel.<locals>._live_history_update at 0x149ef51c0>, <function create_jupyter_panel.<locals>._live_code_update at 0x149ef60c0>], _redo_stack=[])

In [31]:
# 分箱散点图：工资 vs 教育年限，控制工作经验（二次拟合）
# Binscatter: wage vs education controlling for experience (quadratic fit)
fig, ax, _ = sp.binscatter(
    df_iv, y='wage', x='education',
    controls=['experience'],
    n_bins=25, ci=True,
    fit='quadratic',
    figsize=(9, 6),
)
ax.set_title('Binscatter: Wage vs Education\n(controlling for experience, quadratic fit)', fontsize=12)
sp.interactive(fig)

HBox(children=(VBox(children=(Image(value=b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x03v\x00\x00\x02q\x08\…

FigureEditor(fig=<Figure size 1350x900 with 1 Axes>, protect_data=True, edits=[], artist_roles={5359723280: <ArtistRole.LABEL: 5>, 5535479376: <ArtistRole.LABEL: 5>, 5359786448: <ArtistRole.LABEL: 5>, 5535113360: <ArtistRole.SPINE: 8>, 5359542608: <ArtistRole.SPINE: 8>, 5309230032: <ArtistRole.SPINE: 8>, 5309930576: <ArtistRole.SPINE: 8>, 5535478928: <ArtistRole.REFERENCE: 4>, 5359467856: <ArtistRole.REFERENCE: 4>, 5359453264: <ArtistRole.DATA: 1>, 5359260880: <ArtistRole.DATA: 1>, 5308647568: <ArtistRole.CI: 3>}, _original_state={'ax.title.text': 'Binscatter: Wage vs Education\n(controlling for experience, quadratic fit)', 'ax.title.fontsize': 12.0, 'ax.title.color': 'black', 'ax.title.fontweight': 'normal', 'ax.xlabel.text': 'education', 'ax.xlabel.fontsize': 11.0, 'ax.xlabel.color': 'black', 'ax.ylabel.text': 'wage', 'ax.ylabel.fontsize': 11.0, 'ax.ylabel.color': 'black', 'ax.xlim': (np.float64(7.391837015178976), np.float64(16.640096996074455)), 'ax.ylim': (np.float64(17.60176444171628), np.float64(26.941871372749723)), 'ax.facecolor': (1.0, 1.0, 1.0, 1.0), 'ax.xtick_rotation': 0.0, 'ax.ytick_rotation': 0.0, 'ax.spines.left.visible': True, 'ax.spines.right.visible': False, 'ax.spines.bottom.visible': True, 'ax.spines.top.visible': False, 'ax.grid': False, 'ax.line0.color': '#2C3E50', 'ax.line0.linewidth': 0.8, 'ax.line0.linestyle': 'None', 'ax.line0.alpha': 0.6, 'ax.line0.marker': '_', 'ax.line1.color': '#2C3E50', 'ax.line1.linewidth': 0.8, 'ax.line1.linestyle': 'None', 'ax.line1.alpha': 0.6, 'ax.line1.marker': '_', 'ax.line2.color': '#2C3E50', 'ax.line2.linewidth': 1.5, 'ax.line2.linestyle': '-', 'ax.line2.alpha': 0.8, 'ax.line2.marker': 'None', 'ax.coll0.alpha': 0.85, 'ax.coll0.facecolors': array([[0.17254902, 0.24313725, 0.31372549, 0.85      ]]), 'ax.coll1.alpha': 0.6, 'ax.coll1.facecolors': array([], shape=(0, 4), dtype=float64), 'ax.n_texts': 0, 'fig.figsize': (np.float64(9.0), np.float64(6.0)), 'fig.dpi': 150.0, 'fig.facecolor': (1.0, 1.0, 1.0, 1.0)}, _on_refresh_callbacks=[<function create_jupyter_panel.<locals>._live_refresh at 0x149ec5260>, <function create_jupyter_panel.<locals>._live_history_update at 0x14a0036a0>, <function create_jupyter_panel.<locals>._live_code_update at 0x14a054680>], _redo_stack=[])

In [32]:
# 按组分箱散点图：收入 vs 年龄，按处理状态分组
# Binscatter by group: earnings vs age, split by treatment
fig, ax, _ = sp.binscatter(
    df_match, y='earnings', x='age',
    by='treatment',
    n_bins=20, ci=True,
    fit='linear',
    figsize=(9, 6),
)
ax.set_title('Binscatter: Earnings vs Age by Treatment Status', fontsize=13)
ax.set_xlabel('Age', fontsize=11)
ax.set_ylabel('Earnings ($)', fontsize=11)
sp.interactive(fig)

HBox(children=(VBox(children=(Image(value=b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x03v\x00\x00\x02_\x08\…

FigureEditor(fig=<Figure size 1350x900 with 1 Axes>, protect_data=True, edits=[], artist_roles={5536571984: <ArtistRole.LABEL: 5>, 5536872016: <ArtistRole.LABEL: 5>, 5536331472: <ArtistRole.LABEL: 5>, 5536866448: <ArtistRole.SPINE: 8>, 5535811856: <ArtistRole.SPINE: 8>, 5535529040: <ArtistRole.SPINE: 8>, 5536035792: <ArtistRole.SPINE: 8>, 5536198608: <ArtistRole.LEGEND: 7>, 5536866704: <ArtistRole.REFERENCE: 4>, 5359549008: <ArtistRole.REFERENCE: 4>, 5535114960: <ArtistRole.DATA: 1>, 5535697872: <ArtistRole.REFERENCE: 4>, 5359374736: <ArtistRole.REFERENCE: 4>, 5536905936: <ArtistRole.DATA: 1>, 5359802640: <ArtistRole.DATA: 1>, 5537002640: <ArtistRole.CI: 3>, 5536697040: <ArtistRole.DATA: 1>, 5536699792: <ArtistRole.CI: 3>}, _original_state={'ax.title.text': 'Binscatter: Earnings vs Age by Treatment Status', 'ax.title.fontsize': 13.0, 'ax.title.color': 'black', 'ax.title.fontweight': 'normal', 'ax.xlabel.text': 'Age', 'ax.xlabel.fontsize': 11.0, 'ax.xlabel.color': 'black', 'ax.ylabel.text': 'Earnings ($)', 'ax.ylabel.fontsize': 11.0, 'ax.ylabel.color': 'black', 'ax.xlim': (np.float64(15.194039601853877), np.float64(53.695488158841044)), 'ax.ylim': (np.float64(44491.11862702388), np.float64(56187.279431778414)), 'ax.facecolor': (1.0, 1.0, 1.0, 1.0), 'ax.xtick_rotation': 0.0, 'ax.ytick_rotation': 0.0, 'ax.spines.left.visible': True, 'ax.spines.right.visible': False, 'ax.spines.bottom.visible': True, 'ax.spines.top.visible': False, 'ax.grid': False, 'ax.line0.color': '#2C3E50', 'ax.line0.linewidth': 0.8, 'ax.line0.linestyle': 'None', 'ax.line0.alpha': 0.6, 'ax.line0.marker': '_', 'ax.line1.color': '#2C3E50', 'ax.line1.linewidth': 0.8, 'ax.line1.linestyle': 'None', 'ax.line1.alpha': 0.6, 'ax.line1.marker': '_', 'ax.line2.color': '#2C3E50', 'ax.line2.linewidth': 1.5, 'ax.line2.linestyle': '-', 'ax.line2.alpha': 0.8, 'ax.line2.marker': 'None', 'ax.line3.color': '#E74C3C', 'ax.line3.linewidth': 0.8, 'ax.line3.linestyle': 'None', 'ax.line3.alpha': 0.6, 'ax.line3.marker': '_', 'ax.line4.color': '#E74C3C', 'ax.line4.linewidth': 0.8, 'ax.line4.linestyle': 'None', 'ax.line4.alpha': 0.6, 'ax.line4.marker': '_', 'ax.line5.color': '#E74C3C', 'ax.line5.linewidth': 1.5, 'ax.line5.linestyle': '-', 'ax.line5.alpha': 0.8, 'ax.line5.marker': 'None', 'ax.coll0.alpha': 0.85, 'ax.coll0.facecolors': array([[0.17254902, 0.24313725, 0.31372549, 0.85      ]]), 'ax.coll1.alpha': 0.6, 'ax.coll1.facecolors': array([], shape=(0, 4), dtype=float64), 'ax.coll2.alpha': 0.85, 'ax.coll2.facecolors': array([[0.90588235, 0.29803922, 0.23529412, 0.85      ]]), 'ax.coll3.alpha': 0.6, 'ax.coll3.facecolors': array([], shape=(0, 4), dtype=float64), 'ax.n_texts': 0, 'fig.figsize': (np.float64(9.0), np.float64(6.0)), 'fig.dpi': 150.0, 'fig.facecolor': (1.0, 1.0, 1.0, 1.0)}, _on_refresh_callbacks=[<function create_jupyter_panel.<locals>._live_refresh at 0x149f9b1a0>, <function create_jupyter_panel.<locals>._live_history_update at 0x14a191580>, <function create_jupyter_panel.<locals>._live_code_update at 0x14a192520>], _redo_stack=[])

---
## 8. Multi-Panel Comparison

Combining multiple methods in a single figure for publication.

---
## 8. 多面板对比图

将多种因果推断方法整合到单张图中，适用于学术发表。

In [33]:
# 多面板图：4 种因果推断方法并排展示
# Multi-panel figure: 4 causal methods side by side
fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# Panel A: DID parallel trends
sp.did_plot(
    df_did, y='outcome', time='time', treat='treated',
    treat_time=6, ax=axes[0, 0],
    title='(A) DID: Parallel Trends',
)

# Panel B: RD design
sp.rdplot(
    df_rd, y='gpa', x='test_score', c=60,
    nbins=30, ax=axes[0, 1],
    title='(B) RDD: Scholarship → GPA',
)

# Panel C: Synthetic control trajectory
sp.synthplot(sc_result, type='trajectory',
             ax=axes[1, 0],
             title='(C) SC: Treated vs Synthetic')

# Panel D: Binscatter wage vs education
sp.binscatter(
    df_iv, y='wage', x='education',
    n_bins=20, ci=True, fit='linear',
    ax=axes[1, 1],
)
axes[1, 1].set_title('(D) Binscatter: Wage vs Education', fontsize=11)

fig.suptitle('StatsPAI: Multi-Method Causal Inference', fontsize=15, fontweight='bold', y=1.01)
fig.tight_layout()
sp.interactive(fig)

HBox(children=(VBox(children=(Image(value=b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x05j\x00\x00\x03\xf5\x…

FigureEditor(fig=<Figure size 2100x1500 with 4 Axes>, protect_data=True, edits=[], artist_roles={5537768016: <ArtistRole.LABEL: 5>, 5536642640: <ArtistRole.LABEL: 5>, 5538078224: <ArtistRole.LABEL: 5>, 5536321616: <ArtistRole.SPINE: 8>, 5537344144: <ArtistRole.SPINE: 8>, 5537970128: <ArtistRole.SPINE: 8>, 5537962576: <ArtistRole.SPINE: 8>, 5538116240: <ArtistRole.LEGEND: 7>, 5538541072: <ArtistRole.DATA: 1>, 5538904336: <ArtistRole.REFERENCE: 4>, 5538961296: <ArtistRole.DATA: 1>, 5538313360: <ArtistRole.REFERENCE: 4>, 5538963792: <ArtistRole.ANNOTATION: 6>, 5537666832: <ArtistRole.ANNOTATION: 6>, 5538162960: <ArtistRole.ANNOTATION: 6>, 5537500368: <ArtistRole.LABEL: 5>, 5537672976: <ArtistRole.LABEL: 5>, 5537675600: <ArtistRole.LABEL: 5>, 5537667536: <ArtistRole.SPINE: 8>, 5537669008: <ArtistRole.SPINE: 8>, 5537670096: <ArtistRole.SPINE: 8>, 5537671184: <ArtistRole.SPINE: 8>, 5538588880: <ArtistRole.DATA: 1>, 5538966800: <ArtistRole.DATA: 1>, 5537295440: <ArtistRole.REFERENCE: 4>, 5551764880: <ArtistRole.CI: 3>, 5536706320: <ArtistRole.CI: 3>, 5536861008: <ArtistRole.DATA: 1>, 5538903760: <ArtistRole.DATA: 1>, 5538513232: <ArtistRole.LABEL: 5>, 5538505040: <ArtistRole.LABEL: 5>, 5538507792: <ArtistRole.LABEL: 5>, 5536428432: <ArtistRole.SPINE: 8>, 5538500816: <ArtistRole.SPINE: 8>, 5538502032: <ArtistRole.SPINE: 8>, 5538503248: <ArtistRole.SPINE: 8>, 5552025232: <ArtistRole.LEGEND: 7>, 5538374864: <ArtistRole.DATA: 1>, 5538966160: <ArtistRole.DATA: 1>, 5537295504: <ArtistRole.REFERENCE: 4>, 5537147344: <ArtistRole.CI: 3>, 5538766608: <ArtistRole.LABEL: 5>, 5538725392: <ArtistRole.LABEL: 5>, 5538760976: <ArtistRole.LABEL: 5>, 5538719504: <ArtistRole.SPINE: 8>, 5538721168: <ArtistRole.SPINE: 8>, 5538722384: <ArtistRole.SPINE: 8>, 5538723600: <ArtistRole.SPINE: 8>, 5539105488: <ArtistRole.REFERENCE: 4>, 5538805456: <ArtistRole.REFERENCE: 4>, 5552401424: <ArtistRole.DATA: 1>, 5552399504: <ArtistRole.DATA: 1>, 5537198544: <ArtistRole.CI: 3>, 5537071440: <ArtistRole.LABEL: 5>}, _original_state={'ax.title.text': '(A) DID: Parallel Trends', 'ax.title.fontsize': 13.0, 'ax.title.color': 'black', 'ax.title.fontweight': 'normal', 'ax.xlabel.text': 'Time', 'ax.xlabel.fontsize': 11.0, 'ax.xlabel.color': 'black', 'ax.ylabel.text': 'Outcome', 'ax.ylabel.fontsize': 11.0, 'ax.ylabel.color': 'black', 'ax.xlim': (np.float64(0.55), np.float64(10.45)), 'ax.ylim': (np.float64(10.157882537037665), np.float64(20.502018931687)), 'ax.facecolor': (1.0, 1.0, 1.0, 1.0), 'ax.xtick_rotation': 0.0, 'ax.ytick_rotation': 0.0, 'ax.spines.left.visible': True, 'ax.spines.right.visible': False, 'ax.spines.bottom.visible': True, 'ax.spines.top.visible': False, 'ax.grid': False, 'ax.line0.color': '#2C3E50', 'ax.line0.linewidth': 2.0, 'ax.line0.linestyle': '-', 'ax.line0.alpha': None, 'ax.line0.marker': 's', 'ax.line1.color': '#E74C3C', 'ax.line1.linewidth': 2.0, 'ax.line1.linestyle': '-', 'ax.line1.alpha': None, 'ax.line1.marker': 'o', 'ax.line2.color': '#E74C3C', 'ax.line2.linewidth': 1.5, 'ax.line2.linestyle': '--', 'ax.line2.alpha': 0.7, 'ax.line2.marker': '', 'ax.line3.color': 'gray', 'ax.line3.linewidth': 1.0, 'ax.line3.linestyle': ':', 'ax.line3.alpha': 0.5, 'ax.line3.marker': 'None', 'ax.n_texts': 3, 'ax1.title.text': '(B) RDD: Scholarship → GPA', 'ax1.title.fontsize': 13.0, 'ax1.title.color': 'black', 'ax1.title.fontweight': 'normal', 'ax1.xlabel.text': 'test_score', 'ax1.xlabel.fontsize': 11.0, 'ax1.xlabel.color': 'black', 'ax1.ylabel.text': 'gpa', 'ax1.ylabel.fontsize': 11.0, 'ax1.ylabel.color': 'black', 'ax1.xlim': (np.float64(0.07987285086862705), np.float64(112.14412014740388)), 'ax1.ylim': (np.float64(1.2890134144440302), np.float64(5.182182899037506)), 'ax1.facecolor': (1.0, 1.0, 1.0, 1.0), 'ax1.xtick_rotation': 0.0, 'ax1.ytick_rotation': 0.0, 'ax1.spines.left.visible': True, 'ax1.spines.right.visible': False, 'ax1.spines.bottom.visible': True, 'ax1.spines.top.visible': False, 'ax1.grid': False, 'ax1.line0.color': '#E74C3C', 'ax1.line0.linewidth': 1.5, 'ax1.line0.linestyle': '-', 'ax1.line0.alpha': None, 'ax1.line0.marker': 'None', 'ax1.line1.color': '#3498DB', 'ax1.line1.linewidth': 1.5, 'ax1.line1.linestyle': '-', 'ax1.line1.alpha': None, 'ax1.line1.marker': 'None', 'ax1.line2.color': 'gray', 'ax1.line2.linewidth': 0.8, 'ax1.line2.linestyle': '--', 'ax1.line2.alpha': 0.7, 'ax1.line2.marker': 'None', 'ax1.coll0.alpha': 0.12, 'ax1.coll0.facecolors': array([[0.90588235, 0.29803922, 0.23529412, 0.12      ]]), 'ax1.coll1.alpha': 0.12, 'ax1.coll1.facecolors': array([[0.20392157, 0.59607843, 0.85882353, 0.12      ]]), 'ax1.coll2.alpha': 0.8, 'ax1.coll2.facecolors': array([[0.17254902, 0.24313725, 0.31372549, 0.8       ]]), 'ax1.coll3.alpha': 0.8, 'ax1.coll3.facecolors': array([[0.17254902, 0.24313725, 0.31372549, 0.8       ]]), 'ax1.n_texts': 0, 'ax2.title.text': '(C) SC: Treated vs Synthetic', 'ax2.title.fontsize': 13.0, 'ax2.title.color': 'black', 'ax2.title.fontweight': 'normal', 'ax2.xlabel.text': 'Time', 'ax2.xlabel.fontsize': 11.0, 'ax2.xlabel.color': 'black', 'ax2.ylabel.text': 'Outcome', 'ax2.ylabel.fontsize': 11.0, 'ax2.ylabel.color': 'black', 'ax2.xlim': (np.float64(1999.05), np.float64(2019.95)), 'ax2.ylim': (np.float64(47.12487078585494), np.float64(66.01208356282729)), 'ax2.facecolor': (1.0, 1.0, 1.0, 1.0), 'ax2.xtick_rotation': 0.0, 'ax2.ytick_rotation': 0.0, 'ax2.spines.left.visible': True, 'ax2.spines.right.visible': False, 'ax2.spines.bottom.visible': True, 'ax2.spines.top.visible': False, 'ax2.grid': False, 'ax2.line0.color': '#2C3E50', 'ax2.line0.linewidth': 2.2, 'ax2.line0.linestyle': '-', 'ax2.line0.alpha': None, 'ax2.line0.marker': 'None', 'ax2.line1.color': '#E74C3C', 'ax2.line1.linewidth': 2.2, 'ax2.line1.linestyle': '--', 'ax2.line1.alpha': None, 'ax2.line1.marker': 'None', 'ax2.line2.color': '#95A5A6', 'ax2.line2.linewidth': 1.2, 'ax2.line2.linestyle': ':', 'ax2.line2.alpha': 0.8, 'ax2.line2.marker': 'None', 'ax2.coll0.alpha': 0.12, 'ax2.coll0.facecolors': array([[0.90588235, 0.29803922, 0.23529412, 0.12      ]]), 'ax2.n_texts': 0, 'ax3.title.text': '(D) Binscatter: Wage vs Education', 'ax3.title.fontsize': 11.0, 'ax3.title.color': 'black', 'ax3.title.fontweight': 'normal', 'ax3.xlabel.text': 'education', 'ax3.xlabel.fontsize': 11.0, 'ax3.xlabel.color': 'black', 'ax3.ylabel.text': 'wage', 'ax3.ylabel.fontsize': 11.0, 'ax3.ylabel.color': 'black', 'ax3.xlim': (np.float64(7.599019194645182), np.float64(16.437878964863526)), 'ax3.ylim': (np.float64(17.835103299753403), np.float64(26.791518328274588)), 'ax3.facecolor': (1.0, 1.0, 1.0, 1.0), 'ax3.xtick_rotation': 0.0, 'ax3.ytick_rotation': 0.0, 'ax3.spines.left.visible': True, 'ax3.spines.right.visible': False, 'ax3.spines.bottom.visible': True, 'ax3.spines.top.visible': False, 'ax3.grid': False, 'ax3.line0.color': '#2C3E50', 'ax3.line0.linewidth': 0.8, 'ax3.line0.linestyle': 'None', 'ax3.line0.alpha': 0.6, 'ax3.line0.marker': '_', 'ax3.line1.color': '#2C3E50', 'ax3.line1.linewidth': 0.8, 'ax3.line1.linestyle': 'None', 'ax3.line1.alpha': 0.6, 'ax3.line1.marker': '_', 'ax3.line2.color': '#2C3E50', 'ax3.line2.linewidth': 1.5, 'ax3.line2.linestyle': '-', 'ax3.line2.alpha': 0.8, 'ax3.line2.marker': 'None', 'ax3.coll0.alpha': 0.85, 'ax3.coll0.facecolors': array([[0.17254902, 0.24313725, 0.31372549, 0.85      ]]), 'ax3.coll1.alpha': 0.6, 'ax3.coll1.facecolors': array([], shape=(0, 4), dtype=float64), 'ax3.n_texts': 0, 'fig.figsize': (np.float64(14.0), np.float64(10.0)), 'fig.dpi': 150.0, 'fig.facecolor': (1.0, 1.0, 1.0, 1.0), 'fig.suptitle.text': 'StatsPAI: Multi-Method Causal Inference', 'fig.suptitle.fontsize': 15.0}, _on_refresh_callbacks=[<function create_jupyter_panel.<locals>._live_refresh at 0x14af80b80>, <function create_jupyter_panel.<locals>._live_history_update at 0x14b1b3ce0>, <function create_jupyter_panel.<locals>._live_code_update at 0x14b20cc20>], _redo_stack=[])

---
## Summary

| # | Method | Key Function | Plot Functions | Interactive |
|---|--------|-------------|----------------|-------------|
| 1 | **DID** | `sp.did(...)` | `sp.did_plot()`, `sp.event_study_plot()` | `sp.interactive(fig)` |
| 2 | **FE** | `sp.panel(..., method='fe')` | `sp.coefplot()` | `sp.interactive(fig)` |
| 3 | **IV** | `sp.iv("y ~ (endog ~ inst) + exog")` | `sp.coefplot()` | `sp.interactive(fig)` |
| 4 | **Matching** | `sp.match(...)` | `sp.balanceplot()`, `sp.psplot()` | `sp.interactive(fig)` |
| 5 | **SC** | `sp.synth(...)` | `sp.synthplot(..., type=)` | `sp.interactive(fig)` |
| 6 | **RDD** | `sp.rdrobust(...)` | `sp.rdplot()`, `sp.rdplotdensity()` | `sp.interactive(fig)` |
| 7 | **Binscatter** | `sp.binscatter(...)` | built-in | `sp.interactive(fig)` |

### Interactive Editing Tips

- **New in this version**: DPI slider, figure size presets, background color, tick rotation, annotations, grid style, copy-to-clipboard
- Use `sp.get_code(fig)` to extract reproducible code after editing
- All edits are cosmetic only — statistical data is locked and protected

---
## 总结

| # | 方法 | 核心函数 | 绘图函数 | 交互式 |
|---|------|---------|---------|--------|
| 1 | **双重差分法** | `sp.did(...)` | `sp.did_plot()`, `sp.event_study_plot()` | `sp.interactive(fig)` |
| 2 | **固定效应** | `sp.panel(..., method='fe')` | `sp.coefplot()` | `sp.interactive(fig)` |
| 3 | **工具变量** | `sp.iv("y ~ (endog ~ inst) + exog")` | `sp.coefplot()` | `sp.interactive(fig)` |
| 4 | **匹配法** | `sp.match(...)` | `sp.balanceplot()`, `sp.psplot()` | `sp.interactive(fig)` |
| 5 | **合成控制** | `sp.synth(...)` | `sp.synthplot(..., type=)` | `sp.interactive(fig)` |
| 6 | **断点回归** | `sp.rdrobust(...)` | `sp.rdplot()`, `sp.rdplotdensity()` | `sp.interactive(fig)` |
| 7 | **分箱散点图** | `sp.binscatter(...)` | 内置 | `sp.interactive(fig)` |

### 交互式编辑提示

- **本版新增**：DPI 滑块、图形大小预设、背景颜色、刻度旋转、注释、网格样式、复制到剪贴板
- 使用 `sp.get_code(fig)` 在编辑后提取可复现代码
- 所有编辑仅影响外观 —— 统计数据被锁定保护，不会被修改